import {
  Crosshair,
  Hammer,
  HeartPulse,
  Leaf,
  Shield,
  Skull,
  Sword,
  User,
  Wand2,
} from 'lucide-react';
import { safeNumber } from './math';

const PLAYER = {
  radius: 18,
  speed: 260,
  manaRegen: 7,
  hpRegen: 5,
  outOfCombatDelay: 5000,
};

const ENEMY = {
  maxCount: 18,
  radius: 17,
  speed: 155,
  spawnEvery: 1200,
  wanderSpeed: 72,
};

const SAVE_KEY = 'mmo-project.characters.v1';
const FRIENDS_KEY = 'mmo-project.friends.v1';
const REMEMBER_LOGIN_KEY = 'mmo-project.remember-login.v1';
const ADMIN_EMAILS = new Set(['romvariszabi03@gmail.com']);
const MAX_LEVEL = 30;
const ENEMY_XP = 35;
const BOSS_XP = 180;
const BOSS_SPAWN_MIN = 18000;
const BOSS_SPAWN_MAX = 34000;
const BOSS_RESPAWN_DELAY = 60000;
const COLYSEUS_INPUT_MS = 50;
const COLYSEUS_RECONNECT_MS = 1800;
const COLYSEUS_MAX_RECONNECT_ATTEMPTS = 3;
const REMOTE_PLAYER_LEAD_MS = 90;
const REMOTE_PLAYER_SMOOTHING = 15;
const REMOTE_PLAYER_SNAP_DISTANCE = 360;
const AUTO_ATTACK_BASE_COOLDOWN_MS = 900;
const AUTO_ATTACK_MIN_COOLDOWN_MS = 360;
const AUTO_ATTACK_MAX_COOLDOWN_MS = 1600;
const CHANNEL_MAX_DURATION_MS = 600000;
const BASE_STATS = {
  health: 100,
  mana: 60,
  strength: 5,
  agility: 5,
  intellect: 5,
  attackSpeed: 1,
};

const STAT_DESCRIPTIONS = {
  health: 'Maximum health. If it reaches 0, you die.',
  mana: 'Caster resource used by magical and ranged abilities.',
  fury: 'Warrior resource generated by attacks and spent on abilities.',
  energy: 'Rogue resource that regenerates quickly and fuels abilities.',
  strength: 'Increases melee and physical damage.',
  agility: 'Increases bow, dagger and attack speed scaling.',
  intellect: 'Increases spell damage, healing and mana scaling.',
  attackSpeed: 'Multiplies auto attack speed. Higher is faster.',
};

const INVENTORY_CAPACITY = 28;
const RECALL_ITEM_ID = 'account-recall-stone';
const RECALL_CAST_MS = 5000;
const RECALL_ITEM = {
  id: RECALL_ITEM_ID,
  name: 'Recall Stone',
  rarity: 'Rare',
  type: 'usable',
  action: 'recall',
  slot: null,
  stats: {},
  nonDestroyable: true,
  soulbound: true,
  foundAt: 'system',
  description: 'Use: after 5 seconds, teleports you to the nearest respawn point.',
};
const STARTER_HEALTH_POTION_ID = 'starter-health-potion-stack';
const POTION_COOLDOWN_MS = 15000;
const BANK_CAPACITY = 60;
const AUCTION_LISTINGS_KEY = 'mmo-auction-house-listings-v1';
const STARTER_HEALTH_POTION = {
  id: STARTER_HEALTH_POTION_ID,
  name: 'Lesser Healing Potion',
  rarity: 'Common',
  type: 'potion',
  potionType: 'health',
  action: 'heal',
  slot: null,
  stats: {},
  quantity: 8,
  maxStack: 20,
  stackable: true,
  healAmount: 145,
  foundAt: 'system',
  description: 'Restores 145 health. Assign as main potion and press Q to use.',
};
const POTION_TEMPLATES = {
  lesser_healing_potion: {
    name: 'Lesser Healing Potion',
    rarity: 'Common',
    type: 'potion',
    potionType: 'health',
    action: 'heal',
    quantity: 1,
    maxStack: 20,
    stackable: true,
    healAmount: 145,
    price: 5,
    description: 'Restores 145 health.',
  },
  healing_potion: {
    name: 'Healing Potion',
    rarity: 'Uncommon',
    type: 'potion',
    potionType: 'health',
    action: 'heal',
    quantity: 1,
    maxStack: 20,
    stackable: true,
    healAmount: 285,
    price: 14,
    description: 'Restores 285 health.',
  },
  mana_potion: {
    name: 'Mana Potion',
    rarity: 'Uncommon',
    type: 'potion',
    potionType: 'mana',
    action: 'restoreMana',
    quantity: 1,
    maxStack: 20,
    stackable: true,
    manaAmount: 180,
    price: 12,
    description: 'Restores 180 mana.',
  },
};
const CITY_VENDOR_STOCK = {
  general: [
    { id: 'lesser_healing_potion', item: POTION_TEMPLATES.lesser_healing_potion },
    { id: 'healing_potion', item: POTION_TEMPLATES.healing_potion },
  ],
  alchemy: [
    { id: 'lesser_healing_potion', item: POTION_TEMPLATES.lesser_healing_potion },
    { id: 'healing_potion', item: POTION_TEMPLATES.healing_potion },
    { id: 'mana_potion', item: POTION_TEMPLATES.mana_potion },
  ],
  weaponsmith: [
    { id: 'asterfall_iron_sword', item: { name: 'Asterfall Iron Sword', rarity: 'Uncommon', type: 'weapon', slot: 'weapon', stats: { strength: 5, attackSpeed: 0.03 }, price: 32 } },
    { id: 'willow_shortbow', item: { name: 'Willow Shortbow', rarity: 'Uncommon', type: 'weapon', slot: 'weapon', stats: { agility: 5, attackSpeed: 0.04 }, price: 32 } },
    { id: 'apprentice_wand', item: { name: 'Apprentice Wand', rarity: 'Uncommon', type: 'weapon', slot: 'weapon', stats: { intellect: 5, mana: 18 }, price: 34 } },
  ],
  armorer: [
    { id: 'guard_chain_chest', item: { name: 'Guard Chain Chest', rarity: 'Uncommon', type: 'armor', slot: 'chest', stats: { health: 38, strength: 2 }, price: 36 } },
    { id: 'travelers_boots', item: { name: "Traveler's Boots", rarity: 'Uncommon', type: 'armor', slot: 'boots', stats: { health: 18, agility: 2 }, price: 22 } },
  ],
  arcane: [
    { id: 'moonlit_offhand', item: { name: 'Moonlit Offhand', rarity: 'Uncommon', type: 'offhand', slot: 'offhand', stats: { intellect: 4, mana: 30 }, price: 30 } },
    { id: 'adept_ring', item: { name: 'Adept Ring', rarity: 'Rare', type: 'ring', slot: 'ring', stats: { intellect: 4, mana: 22 }, price: 52 } },
  ],
  stable: [
    { id: 'trail_rations', item: { name: 'Trail Rations', rarity: 'Common', type: 'potion', potionType: 'health', action: 'heal', quantity: 1, maxStack: 20, stackable: true, healAmount: 90, price: 3, description: 'A cheap field recovery item.' } },
  ],
};
const PROFESSIONS = [
  { id: 'fishing', displayName: 'Fishing', description: 'Catch fish and water materials near rivers, lakes, and docks.' },
  { id: 'mining', displayName: 'Mining', description: 'Gather ore from rocky highlands, caves, and mountain routes.' },
  { id: 'leatherworking', displayName: 'Leatherworking', description: 'Turn hides into leather armor and utility gear.' },
  { id: 'tailoring', displayName: 'Tailoring', description: 'Craft cloth armor, bags, and caster-focused gear.' },
  { id: 'blacksmithing', displayName: 'Blacksmithing', description: 'Forge weapons, plate armor, and repair supplies.' },
];
const PROFESSION_BY_ID = Object.fromEntries(PROFESSIONS.map((profession) => [profession.id, profession]));
const ABILITY_BAR_SLOTS = 5;
const TALENT_UNLOCK_LEVEL = 10;

const HUNTER_PET = {
  followDistance: 58,
  leashDistance: 320,
  speed: 240,
  radius: 16,
  attackRange: 58,
  attackCooldown: 880,
  damage: 58,
};

const EQUIPMENT_SLOTS = [
  { id: 'head', label: 'Head' },
  { id: 'chest', label: 'Chest' },
  { id: 'legs', label: 'Legs' },
  { id: 'boots', label: 'Boots' },
  { id: 'weapon', label: 'Weapon' },
  { id: 'offhand', label: 'Offhand' },
  { id: 'ring', label: 'Ring' },
  { id: 'trinket', label: 'Trinket' },
];

const STAT_GROWTH = {
  mage: { health: 8, mana: 16, strength: 1, agility: 1, intellect: 4, attackSpeed: 0.01 },
  hunter: { health: 11, mana: 8, strength: 2, agility: 4, intellect: 1, attackSpeed: 0.035 },
  paladin: { health: 14, mana: 10, strength: 3, agility: 1, intellect: 2, attackSpeed: 0.02 },
  warrior: { health: 16, mana: 4, strength: 4, agility: 2, intellect: 0, attackSpeed: 0.025 },
  priest: { health: 9, mana: 15, strength: 1, agility: 1, intellect: 4, attackSpeed: 0.015 },
  rogue: { health: 10, mana: 8, strength: 2, agility: 5, intellect: 1, attackSpeed: 0.055 },
};

const ABILITY_MANA_COST = {
  1: 12,
  2: 18,
  3: 26,
  4: 36,
  5: 48,
  6: 62,
};

const ABILITY_COOLDOWNS = {
  strike: 900,
  cleave: 1200,
  shot: 1100,
  bolt: 1150,
  chain: 5200,
  aura: 6500,
  ground: 9000,
  hot: 2500,
  healGround: 8500,
  buff: 12000,
  nova: 2600,
  trap: 3200,
  shield: 4200,
  shout: 3600,
  heal: 1600,
  channel: 4800,
};

function getAbilityTickRateMs(ability) {
  if (!ability) return 500;
  const fallback = ability.type === 'ground' || ability.type === 'healGround' || ability.type === 'hot'
    ? 1000
    : 500;
  return Math.max(80, safeNumber(ability.tickRate, fallback));
}

function shouldEffectFollowCaster(ability) {
  if (!ability) return false;
  if (ability.followCaster) return true;
  if (ability.type === 'shield') return true;
  return ability.type === 'buff'
    && Boolean(
      ability.absorb
      || ability.invulnerable
      || ability.invisibility
      || ability.damageReduction
      || ability.regenPerSecond
      || ability.autoDamageMultiplier
      || ability.strikeDamageMultiplier
      || ability.poisonWindow
      || ability.noEnergyCost
      || ability.noManaCost
      || ability.cooldownMultiplier
      || ability.stealthDamageMultiplier
      || ability.manaRegenPerSecond
      || ability.furyRegenPerSecond
      || ability.attackSpeedMultiplier
      || ability.petAttackSpeedMultiplier
      || ability.burnWindow
      || ability.rootSelf
      || ability.maxHealthMultiplier
      || ability.autoCombatBolt
      || ability.healingMultiplier
      || ability.damageMultiplier
      || ability.leechPercent,
    );
}

const TALENTS = {
  paladin: {
    unlockLevel: 10,
    specs: {
      verdict: {
        name: 'Oath of the Verdict',
        role: 'Damage',
        description: 'Holy strikes become sharper and faster.',
        bonuses: { strength: 5, intellect: 2, mana: 15 },
        abilities: [
          { key: '1', level: 10, name: 'Crusader Swing', type: 'strike', color: '#fde68a', damage: 96, manaCost: 28, cooldown: 950 },
          {
            key: '2',
            level: 10,
            name: 'Hammerstorm',
            type: 'aura',
            color: '#facc15',
            damage: 34,
            manaCost: 42,
            duration: 2000,
            tickRate: 500,
            radius: 116,
            followCaster: true,
            cooldown: 6500,
          },
          {
            key: '3',
            level: 12,
            name: 'Consecrated Field',
            type: 'ground',
            color: '#fef3c7',
            damage: 46,
            manaCost: 58,
            duration: 5000,
            tickRate: 1000,
            radius: 112,
            groundAtCursor: true,
            cooldown: 9000,
          },
          {
            key: '4',
            level: 16,
            name: "Zealot's Edge",
            type: 'buff',
            color: '#fff7ad',
            manaCost: 36,
            duration: 7000,
            autoDamageMultiplier: 1.65,
            strikeDamageMultiplier: 1.65,
            cooldown: 14000,
          },
        ],
      },
      aegis: {
        name: 'Aegis of Dawn',
        role: 'Tank',
        description: 'You constantly draw enemy focus while fighting.',
        bonuses: { health: 55, strength: 2, intellect: 2, mana: 20 },
        passive: 'Radiant Taunt',
        abilities: [
          { key: '1', level: 10, name: 'Shield Slam', type: 'strike', color: '#bfdbfe', damage: 68, manaCost: 22, cooldown: 950 },
          {
            key: '2',
            level: 10,
            name: "Avenger's Shield",
            type: 'chain',
            color: '#fef08a',
            damage: 56,
            manaCost: 34,
            range: 430,
            maxTargets: 5,
            chainRange: 230,
            segmentMs: 220,
            combatOnly: true,
            cooldown: 6800,
          },
          {
            key: '3',
            level: 12,
            name: 'Guardian Hammers',
            type: 'aura',
            color: '#fde68a',
            damage: 24,
            manaCost: 46,
            duration: 5000,
            tickRate: 500,
            radius: 112,
            followCaster: true,
            cooldown: 10500,
          },
          {
            key: '4',
            level: 16,
            name: 'Bastion Renewal',
            type: 'buff',
            color: '#e0f2fe',
            manaCost: 42,
            duration: 7000,
            damageReduction: 0.45,
            regenPerSecond: 18,
            cooldown: 16000,
          },
        ],
      },
    },
  },
  warrior: {
    unlockLevel: 10,
    specs: {
      berserker: {
        name: 'Blood Fury',
        role: 'Damage',
        description: 'Builds fury through aggressive slashes, then spends it on wide melee pressure.',
        bonuses: { strength: 6, agility: 2, health: 18, fury: 20 },
        abilities: [
          { key: '1', level: 10, name: 'Slash', type: 'strike', color: '#f97316', damage: 82, furyCost: 0, furyGain: 10, cooldown: 850, range: 96, width: 48 },
          { key: '2', level: 10, name: 'Sweeping Slash', type: 'cleave', color: '#fb923c', damage: 92, furyCost: 22, cooldown: 2600, range: 145, arc: 0.95, width: 70 },
          { key: '3', level: 12, name: 'Double Slash', type: 'cleave', color: '#fecaca', damage: 56, furyCost: 28, cooldown: 5200, range: 120, arc: 0.75, width: 64, multiStrike: 2 },
          { key: '4', level: 16, name: 'Bladestorm', type: 'aura', color: '#ef4444', damage: 42, furyCost: 38, duration: 4000, tickRate: 500, radius: 126, followCaster: true, cooldown: 14000 },
        ],
      },
      ironward: {
        name: 'Iron Ward',
        role: 'Tank',
        description: 'Generates fury with shield attacks and converts it into mitigation and self-healing.',
        bonuses: { health: 70, strength: 4, agility: 1, fury: 15 },
        passive: 'Shield Discipline',
        abilities: [
          { key: '1', level: 10, name: 'Shield Slam', type: 'strike', color: '#cbd5e1', damage: 70, furyCost: 0, furyGain: 12, cooldown: 900, range: 90, width: 48 },
          { key: '2', level: 10, name: 'Shield Sweep', type: 'nova', color: '#94a3b8', damage: 62, furyCost: 24, radius: 112, cooldown: 5200 },
          { key: '3', level: 12, name: 'Guard Wall', type: 'buff', color: '#e5e7eb', furyCost: 32, duration: 6000, absorb: 95, damageReduction: 0.35, followCaster: true, cooldown: 15000 },
          { key: '4', level: 16, name: 'Vanguard Cleave', type: 'cleave', color: '#d1d5db', damage: 86, furyCost: 34, range: 130, arc: 0.9, selfHealPercent: 0.28, cooldown: 7600 },
        ],
      },
    },
  },
  hunter: {
    unlockLevel: 10,
    specs: {
      beastmaster: {
        name: 'Sharpshooter',
        role: 'Damage',
        description: 'Long-range bow pressure with multishot, rapid fire, and armor-piercing mark shots.',
        bonuses: { agility: 7, strength: 1, mana: 20, attackSpeed: 0.08 },
        passive: 'Loyal Pet',
        abilities: [
          { key: '1', level: 10, name: 'Steady Shot', type: 'shot', color: '#fde68a', damage: 72, manaCost: 18, range: 590, width: 22, cooldown: 850 },
          { key: '2', level: 10, name: 'Multishot', type: 'cleave', color: '#bef264', damage: 74, manaCost: 34, range: 420, arc: 0.55, width: 96, cooldown: 5200 },
          { key: '3', level: 12, name: 'Rapid Fire', type: 'channel', color: '#facc15', damage: 28, manaCost: 10, duration: 3600, tickRate: 300, range: 590, width: 28, cooldown: 10500, followCaster: true },
          { key: '4', level: 16, name: 'Piercing Shot', type: 'shot', color: '#fef08a', damage: 132, manaCost: 54, range: 660, width: 42, pierce: true, cooldown: 11000 },
        ],
      },
      survival: {
        name: 'Wildstalker',
        role: 'Damage',
        description: 'Poison arrows, traps, arrow rain, and pet bleed burst windows.',
        bonuses: { agility: 5, health: 28, mana: 18, attackSpeed: 0.05 },
        passive: 'Loyal Pet',
        abilities: [
          { key: '1', level: 10, name: 'Barbed Shot', type: 'shot', color: '#86efac', damage: 68, manaCost: 18, range: 560, width: 22, cooldown: 900 },
          { key: '2', level: 10, name: 'Poison Arrow', type: 'shot', color: '#65a30d', damage: 54, manaCost: 32, range: 570, width: 24, applyPoison: true, poisonDamage: 9, poisonDuration: 5000, poisonTickRate: 1000, cooldown: 4800 },
          { key: '3', level: 12, name: 'Explosive Trap', type: 'trap', color: '#fb923c', damage: 34, manaCost: 42, duration: 15000, tickRate: 160, radius: 104, trapOffset: 120, slowDuration: 3000, slowMultiplier: 0.55, cooldown: 9000 },
          { key: '4', level: 16, name: 'Arrow Rain', type: 'ground', color: '#fde047', damage: 34, manaCost: 58, duration: 4000, tickRate: 500, radius: 132, groundAtCursor: true, cooldown: 11500 },
        ],
      },
    },
  },
  mage: {
    unlockLevel: 10,
    specs: {
      frost: {
        name: 'Frostbinder',
        role: 'Damage',
        description: 'Frost spells apply Cold for 3 seconds, slowing enemies before shattering them.',
        bonuses: { intellect: 6, mana: 26, health: 12 },
        passive: 'Cold Snap',
        abilities: [
          { key: '1', level: 10, name: 'Frost Bolt', type: 'bolt', color: '#7dd3fc', damage: 76, manaCost: 22, range: 560, width: 24, cooldown: 950, applyCold: true, slowDuration: 3000, slowMultiplier: 0.55 },
          { key: '2', level: 10, name: 'Frozen Circle', type: 'ground', color: '#bae6fd', damage: 22, manaCost: 46, duration: 520, tickRate: 520, radius: 118, groundAtCursor: true, freezeDuration: 2200, cooldown: 11000 },
          { key: '3', level: 12, name: 'Hailstorm', type: 'ground', color: '#e0f2fe', damage: 36, manaCost: 56, duration: 4000, tickRate: 500, radius: 126, groundAtCursor: true, cooldown: 12000 },
          { key: '4', level: 16, name: 'Shatter Spike', type: 'bolt', color: '#cffafe', damage: 54, manaCost: 34, range: 570, width: 24, skipCold: true, bonusVsControlledMultiplier: 2.15, cooldown: 4200 },
        ],
      },
      arcane: {
        name: 'Firecaller',
        role: 'Damage',
        description: 'Fire spells burn enemies and build toward inferno burst windows.',
        bonuses: { intellect: 7, mana: 22, attackSpeed: 0.04 },
        abilities: [
          { key: '1', level: 10, name: 'Fire Bolt', type: 'bolt', color: '#fb923c', damage: 82, manaCost: 24, range: 560, width: 24, cooldown: 950 },
          { key: '2', level: 10, name: 'Fireball', type: 'shot', color: '#ef4444', damage: 80, manaCost: 42, range: 590, width: 34, pierce: true, applyBurn: true, burnDamage: 12, burnDuration: 5000, burnTickRate: 1000, cooldown: 6200 },
          { key: '3', level: 12, name: 'Flame Wave', type: 'aura', color: '#f97316', damage: 46, manaCost: 52, duration: 4000, tickRate: 1000, radius: 118, followCaster: true, cooldown: 11000 },
          { key: '4', level: 16, name: 'Burning Ground', type: 'ground', color: '#fb7185', damage: 38, manaCost: 58, duration: 4000, tickRate: 500, radius: 122, groundAtCursor: true, applyBurn: true, burnDamage: 10, burnDuration: 4500, burnTickRate: 1000, cooldown: 12000 },
        ],
      },
    },
  },
  priest: {
    unlockLevel: 10,
    specs: {
      void: {
        name: 'Enter the Void',
        role: 'Damage',
        description: 'Void magic channels, curses, and turns mana into purple pressure.',
        bonuses: { intellect: 7, mana: 26, attackSpeed: 0.04 },
        abilities: [
          { key: '1', level: 10, name: 'Void Bolt', type: 'bolt', color: '#8b5cf6', damage: 86, manaCost: 24, range: 560, width: 24, cooldown: 950 },
          {
            key: '2',
            level: 10,
            name: 'Flay',
            type: 'channel',
            color: '#5b21b6',
            damage: 30,
            manaCost: 8,
            duration: 3200,
            tickRate: 450,
            range: 570,
            width: 34,
            cooldown: 5200,
            followCaster: true,
          },
          { key: '3', level: 12, name: 'Mind Blast', type: 'ground', color: '#7c3aed', damage: 84, manaCost: 52, duration: 700, tickRate: 700, radius: 108, groundAtCursor: true, cooldown: 7200 },
          { key: '4', level: 16, name: 'Void Curse', type: 'ground', color: '#4c1d95', damage: 28, manaCost: 58, duration: 4000, tickRate: 500, radius: 118, groundAtCursor: true, cooldown: 10500 },
        ],
      },
      light: {
        name: 'Embrace the Light',
        role: 'Healer',
        description: 'Golden healing magic restores allies and bursts into holy protection.',
        bonuses: { health: 25, intellect: 4, mana: 34 },
        abilities: [
          { key: '1', level: 10, name: 'Light Heal', type: 'heal', color: '#fef3c7', healing: 92, manaCost: 34, cooldown: 1800, targetPlayer: true },
          { key: '2', level: 10, name: 'Renew', type: 'hot', color: '#fde68a', healing: 34, manaCost: 30, duration: 6000, tickRate: 1000, cooldown: 4500, targetPlayer: true },
          { key: '3', level: 12, name: 'Radiant Circle', type: 'healGround', color: '#facc15', healing: 50, manaCost: 58, duration: 5000, tickRate: 1000, radius: 125, groundAtCursor: true, cooldown: 10000 },
          { key: '4', level: 16, name: 'Holy Nova', type: 'nova', color: '#fef08a', damage: 42, healing: 58, manaCost: 46, radius: 128, cooldown: 4800 },
        ],
      },
    },
  },
  rogue: {
    unlockLevel: 10,
    specs: {
      nightblade: {
        name: 'Assassin',
        role: 'Damage',
        description: 'Invisibility openers, poison windows, and stacking bleed pressure.',
        bonuses: { agility: 7, strength: 2, attackSpeed: 0.18 },
        abilities: [
          { key: '1', level: 10, name: 'Quick Cut', type: 'strike', color: '#d8b4fe', damage: 86, energyCost: 22, cooldown: 700, range: 76 },
          { key: '2', level: 10, name: 'Assassinate', type: 'strike', color: '#f0abfc', damage: 132, energyCost: 34, cooldown: 2100, range: 82 },
          { key: '3', level: 12, name: 'Fan of Knives', type: 'nova', color: '#a78bfa', damage: 78, energyCost: 42, cooldown: 6200, radius: 142 },
          {
            key: '4',
            level: 16,
            name: 'Poison Blade',
            type: 'buff',
            color: '#86efac',
            energyCost: 28,
            cooldown: 14000,
            duration: 5000,
            poisonWindow: true,
            poisonDamage: 9,
            poisonDuration: 5000,
            poisonTickRate: 1000,
            followCaster: true,
          },
        ],
      },
      duelist: {
        name: 'Shadow',
        role: 'Damage',
        description: 'Teleport pressure, fast dagger flurries, and a short burst window.',
        bonuses: { agility: 5, strength: 4, health: 18, attackSpeed: 0.25 },
        abilities: [
          { key: '1', level: 10, name: 'Shadow Slash', type: 'strike', color: '#c084fc', damage: 82, energyCost: 20, cooldown: 750, range: 76 },
          { key: '2', level: 10, name: 'Shadow Flurry', type: 'channel', color: '#7c3aed', damage: 34, energyCost: 10, duration: CHANNEL_MAX_DURATION_MS, tickRate: 200, cooldown: 3800, range: 58, width: 48, followCaster: true },
          { key: '3', level: 12, name: 'Shadowstep', type: 'strike', color: '#a78bfa', damage: 78, energyCost: 38, cooldown: 9000, range: 260, teleportToTarget: true, postDamageMultiplier: 1.25, postDamageDuration: 2000 },
          { key: '4', level: 16, name: 'Dagger Cyclone', type: 'aura', color: '#e9d5ff', damage: 52, energyCost: 46, duration: 2000, tickRate: 500, cooldown: 12000, radius: 126, followCaster: true },
        ],
      },
    },
  },
};

const TALENT_BRANCHES = [
  { id: 'training', name: 'Training' },
  { id: 'abilities', name: 'Ability Focus' },
  { id: 'mastery', name: 'Mastery' },
];

const TALENT_NODES = [
  {
    id: 'core',
    branch: 'training',
    name: 'Core Discipline',
    maxRank: 3,
    description: 'Improves your primary stat and health.',
  },
  {
    id: 'flow',
    branch: 'training',
    name: 'Battle Flow',
    maxRank: 3,
    description: 'Improves your resource comfort and attack rhythm.',
  },
  {
    id: 'ability1',
    branch: 'abilities',
    name: 'Opening Technique',
    maxRank: 2,
    abilityKey: '1',
    damageBonus: 0.06,
    healingBonus: 0.06,
    description: 'Improves your first specialization ability.',
  },
  {
    id: 'ability2',
    branch: 'abilities',
    name: 'Second Technique',
    maxRank: 2,
    abilityKey: '2',
    damageBonus: 0.06,
    healingBonus: 0.06,
    cooldownReduction: 0.03,
    description: 'Improves your second specialization ability.',
  },
  {
    id: 'ability3',
    branch: 'abilities',
    name: 'Field Control',
    maxRank: 2,
    abilityKey: '3',
    requiresLevel: 12,
    damageBonus: 0.05,
    healingBonus: 0.05,
    cooldownReduction: 0.04,
    description: 'Improves your third specialization ability.',
  },
  {
    id: 'ability4',
    branch: 'mastery',
    name: 'Defining Technique',
    maxRank: 2,
    abilityKey: '4',
    requiresLevel: 16,
    damageBonus: 0.04,
    healingBonus: 0.04,
    durationBonus: 0.08,
    absorbBonus: 0.08,
    description: 'Improves your fourth specialization ability.',
  },
  {
    id: 'ability5',
    branch: 'mastery',
    name: 'Final Technique',
    maxRank: 2,
    abilityKey: '5',
    requiresLevel: 20,
    damageBonus: 0.08,
    healingBonus: 0.08,
    cooldownReduction: 0.05,
    durationBonus: 0.05,
    absorbBonus: 0.08,
    description: 'Improves your fifth specialization ability.',
  },
];

const SPEC_FINAL_ABILITY_LEVEL = 20;

const SPEC_FINAL_ABILITIES = {
  mage: {
    frost: { key: '5', level: SPEC_FINAL_ABILITY_LEVEL, name: 'Ice Block', type: 'buff', color: '#bae6fd', manaCost: 58, duration: 5000, rootSelf: true, invulnerable: true, regenPerSecond: 18, manaRegenPerSecond: 30, autoCombatBolt: true, autoBoltName: 'Frost Bolt', autoBoltDamage: 48, autoBoltInterval: 1000, autoBoltCombatOnly: true, cooldown: 42000, followCaster: true },
    arcane: { key: '5', level: SPEC_FINAL_ABILITY_LEVEL, name: 'Inferno Form', type: 'buff', color: '#fb923c', manaCost: 74, duration: 9000, damageMultiplier: 1.18, manaRegenPerSecond: 22, burnWindow: true, burnDamage: 11, burnDuration: 5000, burnTickRate: 1000, burnStacking: true, cooldown: 36000, followCaster: true },
  },
  hunter: {
    beastmaster: { key: '5', level: SPEC_FINAL_ABILITY_LEVEL, name: 'True Shot', type: 'shot', color: '#fef08a', damage: 165, manaCost: 72, range: 720, width: 58, pierce: true, damageTakenMultiplier: 1.22, damageTakenDuration: 7000, cooldown: 30000 },
    survival: { key: '5', level: SPEC_FINAL_ABILITY_LEVEL, name: 'Predator Focus', type: 'buff', color: '#bef264', manaCost: 66, duration: 10000, attackSpeedMultiplier: 1.35, petAttackSpeedMultiplier: 1.45, petBleedDamage: 10, petBleedDuration: 5000, damageMultiplier: 1.14, cooldown: 36000, followCaster: true },
  },
  paladin: {
    verdict: {
      key: '5',
      level: SPEC_FINAL_ABILITY_LEVEL,
      name: 'Avenging Radiance',
      type: 'buff',
      color: '#fef08a',
      manaCost: 72,
      duration: 9000,
      damageMultiplier: 1.4,
      leechPercent: 0.3,
      cooldown: 30000,
    },
    aegis: {
      key: '5',
      level: SPEC_FINAL_ABILITY_LEVEL,
      name: 'Divine Bulwark',
      type: 'buff',
      color: '#dbeafe',
      manaCost: 62,
      duration: 5000,
      invulnerable: true,
      cooldown: 45000,
    },
  },
  warrior: {
    berserker: { key: '5', level: SPEC_FINAL_ABILITY_LEVEL, name: 'Blood Frenzy', type: 'buff', color: '#ef4444', furyCost: 46, duration: 9000, furyRegenPerSecond: 14, damageMultiplier: 1.28, leechPercent: 0.22, cooldown: 34000, followCaster: true },
    ironward: { key: '5', level: SPEC_FINAL_ABILITY_LEVEL, name: 'Last Stand', type: 'buff', color: '#cbd5e1', furyCost: 42, duration: 9000, maxHealthMultiplier: 1.35, regenPerSecond: 24, damageReduction: 0.35, furyRegenPerSecond: 12, cooldown: 42000, followCaster: true },
  },
  priest: {
    void: {
      key: '5',
      level: SPEC_FINAL_ABILITY_LEVEL,
      name: 'Void Form',
      type: 'buff',
      color: '#4c1d95',
      manaCost: 76,
      duration: 5000,
      manaRegenPerSecond: 34,
      autoCombatBolt: true,
      autoBoltCombatOnly: true,
      autoBoltName: 'Void Bolt',
      autoBoltDamage: 54,
      autoBoltInterval: 500,
      cooldown: 34000,
      followCaster: true,
    },
    light: {
      key: '5',
      level: SPEC_FINAL_ABILITY_LEVEL,
      name: 'Become the Ascended',
      type: 'buff',
      color: '#fef08a',
      manaCost: 78,
      duration: 7000,
      noManaCost: true,
      healingMultiplier: 1.45,
      cooldownMultiplier: 0.55,
      cooldown: 42000,
      followCaster: true,
    },
  },
  rogue: {
    nightblade: { key: '5', level: SPEC_FINAL_ABILITY_LEVEL, name: 'Crimson Rupture', type: 'strike', color: '#dc2626', damage: 118, energyCost: 52, cooldown: 28000, bleedDamage: 16, bleedTickRate: 1000, range: 82 },
    duelist: { key: '5', level: SPEC_FINAL_ABILITY_LEVEL, name: 'Shadow Frenzy', type: 'buff', color: '#312e81', energyCost: 30, duration: 10000, cooldown: 42000, noEnergyCost: true, cooldownMultiplier: 0.35, followCaster: true },
  },
};

const BOSS_LOOT = [
  { name: 'Ancient Ember Crown', rarity: 'Rare', slot: 'head', stats: { intellect: 3, mana: 10 } },
  { name: 'Ironbark Chestguard', rarity: 'Rare', slot: 'chest', stats: { health: 25, strength: 1 } },
  { name: 'Wolf King Fang', rarity: 'Epic', slot: 'weapon', stats: { strength: 4, agility: 2 } },
  { name: 'Moonlit Trail Boots', rarity: 'Epic', slot: 'boots', stats: { agility: 4, health: 10 } },
  { name: 'Sunforged Relic', rarity: 'Epic', slot: 'trinket', stats: { mana: 15, intellect: 2 } },
  { name: 'Rift Guard Buckler', rarity: 'Rare', slot: 'offhand', stats: { health: 18, strength: 2 } },
  { name: 'Band of First Dawn', rarity: 'Rare', slot: 'ring', stats: { agility: 2, intellect: 2 } },
];

const SHOPKEEPER = {
  x: 515,
  y: 390,
  name: 'Mira',
  type: 'shopkeeper',
  interactRange: 92,
};

const RACES = {
  human: {
    name: 'Human',
    icon: User,
    skin: '#f2c7a4',
    hair: '#8b5e34',
    scale: 1,
    allowedClasses: ['mage', 'hunter', 'paladin', 'warrior', 'priest', 'rogue'],
  },
  elf: {
    name: 'Elf',
    icon: Leaf,
    skin: '#f0d6ad',
    hair: '#e9d66b',
    scale: 0.96,
    allowedClasses: ['mage', 'hunter', 'priest', 'rogue'],
  },
  dwarf: {
    name: 'Dwarf',
    icon: Hammer,
    skin: '#d6a06f',
    hair: '#9a4f2f',
    scale: 0.88,
    allowedClasses: ['paladin', 'warrior', 'hunter', 'priest', 'rogue'],
  },
  orc: {
    name: 'Orc',
    icon: Sword,
    skin: '#74a85a',
    hair: '#20251f',
    scale: 1.08,
    allowedClasses: ['warrior', 'hunter', 'rogue'],
  },
  undead: {
    name: 'Undead',
    icon: Skull,
    skin: '#cbd5c0',
    hair: '#d8dee9',
    scale: 1,
    allowedClasses: ['mage', 'warrior', 'priest', 'rogue'],
  },
};

const CLASSES = {
  mage: {
    name: 'Mage',
    icon: Wand2,
    colors: {
      robe: '#4263eb',
      trim: '#8be9fd',
      hair: '#8b5e34',
      weapon: '#d7f9ff',
    },
    abilities: [
      { key: '1', level: 1, name: 'Firebolt', type: 'bolt', color: '#ff6b35', damage: 55 },
      { key: '2', level: 1, name: 'Frost Nova', type: 'nova', color: '#7dd3fc', damage: 30 },
      { key: '3', level: 4, name: 'Arcane Lance', type: 'shot', color: '#c084fc', damage: 65 },
      { key: '4', level: 8, name: 'Meteor Ring', type: 'shout', color: '#fb7185', damage: 42 },
      { key: '5', level: 12, name: 'Ice Prison', type: 'trap', color: '#bae6fd', damage: 70 },
      { key: '6', level: 16, name: 'Star Surge', type: 'bolt', color: '#fef08a', damage: 95 },
    ],
  },
  hunter: {
    name: 'Hunter',
    icon: Crosshair,
    colors: {
      robe: '#2f9e44',
      trim: '#facc15',
      hair: '#8b5e34',
      weapon: '#8d6e45',
    },
    abilities: [
      { key: '1', level: 1, name: 'Piercing Shot', type: 'shot', color: '#facc15', damage: 45 },
      { key: '2', level: 1, name: 'Trap', type: 'trap', color: '#fb923c', damage: 40, duration: 15000, tickRate: 160, radius: 76, trapOffset: 120 },
      { key: '3', level: 4, name: 'Rapid Arrow', type: 'bolt', color: '#bef264', damage: 58 },
      { key: '4', level: 8, name: 'Explosive Trap', type: 'trap', color: '#fdba74', damage: 70, duration: 15000, tickRate: 160, radius: 92, trapOffset: 120 },
      { key: '5', level: 12, name: 'Volley', type: 'shout', color: '#fde047', damage: 45 },
      { key: '6', level: 16, name: 'Deadeye', type: 'shot', color: '#fefce8', damage: 110 },
    ],
  },
  paladin: {
    name: 'Paladin',
    icon: Shield,
    colors: {
      robe: '#e6c55c',
      trim: '#f8fafc',
      hair: '#8b5e34',
      weapon: '#cbd5e1',
    },
    abilities: [
      { key: '1', level: 1, name: 'Holy Strike', type: 'strike', color: '#fff3a3', damage: 45 },
      { key: '2', level: 1, name: 'Divine Shield', type: 'shield', color: '#fef08a', damage: 22 },
      { key: '3', level: 4, name: 'Judgement', type: 'bolt', color: '#fde68a', damage: 62 },
      { key: '4', level: 8, name: 'Consecration', type: 'nova', color: '#fef3c7', damage: 48 },
      { key: '5', level: 12, name: 'Hammer Toss', type: 'shot', color: '#e5e7eb', damage: 82 },
      { key: '6', level: 16, name: 'Radiant Burst', type: 'shout', color: '#fef08a', damage: 72 },
    ],
  },
  warrior: {
    name: 'Warrior',
    icon: Sword,
    colors: {
      robe: '#b42318',
      trim: '#64748b',
      hair: '#2f221d',
      weapon: '#d1d5db',
    },
    abilities: [
      { key: '1', level: 1, name: 'Cleave', type: 'cleave', color: '#f97316', damage: 48 },
      { key: '2', level: 1, name: 'Battle Shout', type: 'shout', color: '#ef4444', damage: 25 },
      { key: '3', level: 4, name: 'Charge Slash', type: 'strike', color: '#fb923c', damage: 65 },
      { key: '4', level: 8, name: 'Whirlwind', type: 'nova', color: '#f87171', damage: 50 },
      { key: '5', level: 12, name: 'Ground Breaker', type: 'trap', color: '#a16207', damage: 80 },
      { key: '6', level: 16, name: 'Execute', type: 'shot', color: '#fecaca', damage: 120 },
    ],
  },
  priest: {
    name: 'Priest',
    icon: HeartPulse,
    colors: {
      robe: '#f8fafc',
      trim: '#facc15',
      hair: '#8b5e34',
      weapon: '#fde68a',
    },
    abilities: [
      { key: '1', level: 1, name: 'Smite', type: 'bolt', color: '#fef3c7', damage: 48 },
      { key: '2', level: 1, name: 'Holy Nova', type: 'nova', color: '#fde68a', damage: 28 },
      { key: '3', level: 4, name: 'Mind Spike', type: 'shot', color: '#c4b5fd', damage: 62 },
      { key: '4', level: 8, name: 'Sanctuary', type: 'shield', color: '#fef08a', damage: 34 },
      { key: '5', level: 12, name: 'Penance', type: 'bolt', color: '#e9d5ff', damage: 78 },
      { key: '6', level: 16, name: 'Divine Wrath', type: 'shout', color: '#fff7ed', damage: 82 },
    ],
  },
  rogue: {
    name: 'Rogue',
    icon: Sword,
    colors: {
      robe: '#312e81',
      trim: '#c084fc',
      hair: '#2f221d',
      weapon: '#e5e7eb',
    },
    abilities: [
      { key: '1', level: 1, name: 'Quick Stab', type: 'strike', color: '#d8b4fe', damage: 44 },
      { key: '2', level: 1, name: 'Blade Fan', type: 'cleave', color: '#a78bfa', damage: 34 },
      { key: '3', level: 4, name: 'Poison Knife', type: 'shot', color: '#86efac', damage: 58 },
      { key: '4', level: 8, name: 'Smoke Bomb', type: 'trap', color: '#94a3b8', damage: 48 },
      { key: '5', level: 12, name: 'Ambush', type: 'strike', color: '#f0abfc', damage: 88 },
      { key: '6', level: 16, name: 'Eviscerate', type: 'shot', color: '#f5d0fe', damage: 118 },
    ],
  },
};

const CLASS_NAME_POOLS = {
  mage: ['Aetherion', 'Lyra Spellwind', 'Vaelis', 'Mira Starfall', 'Eldrin'],
  hunter: ['Rowan Swiftshot', 'Kael Thorn', 'Ashen Vale', 'Nira Wildmark', 'Bryn'],
  paladin: ['Aurel Dawnshield', 'Ser Caldus', 'Tirion Vale', 'Maren Lightward', 'Garran'],
  warrior: ['Brakka Ironhand', 'Duran Steelborn', 'Rokar', 'Hilda Axebreaker', 'Torvik'],
  priest: ['Elowen Lightcall', 'Seren Dawn', 'Iria Solace', 'Neris', 'Calen Vow'],
  rogue: ['Nyx Shade', 'Vera Quickstep', 'Silas Dusk', 'Kira Vex', 'Ren Blackvale'],
};

const CHARACTER_SPRITE_SIZE = 48;
const CHARACTER_SPRITE_DRAW_SIZE = 72;
const CHARACTER_SPRITE_COLUMNS = 6;
const CHARACTER_SPRITE_EXPECTED_WIDTH = CHARACTER_SPRITE_SIZE * CHARACTER_SPRITE_COLUMNS;
const CHARACTER_SPRITE_EXPECTED_HEIGHT = CHARACTER_SPRITE_SIZE * 4;
const CHARACTER_SPRITE_EIGHT_DIRECTION_HEIGHT = CHARACTER_SPRITE_SIZE * 8;
const HUMAN_CHARACTER_SPRITE_COLUMNS = 9;
const HUMAN_CHARACTER_SPRITE_SIZE = 96;
const HUMAN_CHARACTER_SPRITE_EXPECTED_WIDTH = HUMAN_CHARACTER_SPRITE_SIZE * HUMAN_CHARACTER_SPRITE_COLUMNS;
const HUMAN_CHARACTER_SPRITE_EXPECTED_HEIGHT = HUMAN_CHARACTER_SPRITE_SIZE * 8;
const HUMAN_CHARACTER_WALK_COLUMNS = Object.freeze([1, 2, 3, 4]);
const HUMAN_CHARACTER_ATTACK_COLUMNS = Object.freeze([5, 6, 7, 8]);
const CHARACTER_SPRITE_VERSION = 'adventurer-fresh-v3';
const CHARACTER_SPRITE_VARIANTS = ['male', 'female'];
const CHARACTER_SPRITE_ROWS = {
  down: 0,
  left: 1,
  right: 2,
  up: 3,
};
const CHARACTER_SPRITE_ROWS_8 = {
  down: 0,
  'down-right': 1,
  right: 2,
  'up-right': 3,
  up: 4,
  'up-left': 5,
  left: 6,
  'down-left': 7,
};
const CHARACTER_SPRITES = new globalThis.Map();
const CHARACTER_SPRITE_LOADS = new globalThis.Map();
const CHARACTER_TINTED_SPRITES = new globalThis.Map();
const CHARACTER_SPRITE_SOURCE_PALETTES = {
  priest: {
    skin: '#f2c7a4', skinShade: '#d99a72', hair: '#8b5e34',
    robeDeep: '#64748b', robe: '#f8fafc', trim: '#facc15', trimLight: '#fef08a',
  },
  paladin: {
    skin: '#f2c7a4', skinShade: '#d99a72', hair: '#8b5e34',
    robeDeep: '#475569', robe: '#f8fafc', trim: '#facc15', trimLight: '#fef08a',
  },
  hunter: {
    skin: '#f2c7a4', skinShade: '#d99a72', hair: '#8b5e34',
    robeDeep: '#152b18', robe: '#365c2d', trim: '#172554',
  },
  mage: {
    skin: '#f2c7a4', skinShade: '#d99a72', hair: '#8b5e34',
    robeDeep: '#172554', robeMid: '#312e81', robe: '#1d4ed8', robeLight: '#4263eb',
    trimDark: '#0e7490', trim: '#67e8f9', trimLight: '#8be9fd',
  },
  rogue: {
    skin: '#f2c7a4', skinShade: '#d99a72', hair: '#8b5e34',
    robeDeep: '#090f1a', robe: '#1f2937', trim: '#9ca3af', trimLight: '#8b5cf6',
  },
  warrior: {
    skin: '#f2c7a4', skinShade: '#d99a72', hair: '#8b5e34',
    robeDeep: '#3f1210', robe: '#7f1d1d', trim: '#cbd5e1', trimLight: '#94a3b8',
  },
};
const CHARACTER_LAYER_ORDER = [
  'cape',
  'base',
  'hair',
  'outfit',
  'face',
  'heritage',
  'beard',
  'headwear',
  'offhand',
  'weapon',
];
const CHARACTER_LAYER_IMAGES = new globalThis.Map();
const CHARACTER_LAYER_LOADS = new globalThis.Map();
const ENEMY_SPRITES = new globalThis.Map();
const ENEMY_SPRITE_LOADS = new globalThis.Map();
const PET_SPRITES = new globalThis.Map();
const PET_SPRITE_LOADS = new globalThis.Map();
const PET_SPRITE_VERSION = 'pet-attack-v2';
const ENEMY_SPRITE_VERSION = 'saltspine-up-attack-v16';
const SHOW_MAP_ENEMY_DOTS = false;
const MAP_CANVAS_REDRAW_MS = 520;
const WORLD_BOSS_MECHANICS = Object.freeze({
  'tideglass-matriarch': Object.freeze({
    type: 'tidal-volley',
    damage: 78,
    initialDelay: 2200,
    telegraphDuration: 520,
    recoveryDuration: 320,
    cooldown: 5600,
    activationRange: 500,
    maxTravelDistance: 680,
    projectileSpeed: 540,
    projectileRadius: 24,
    projectileCountMin: 3,
    projectileCountMax: 4,
    projectileSpread: 0.14,
    targetLeadMs: 140,
    targetLeadMaxDistance: 56,
    slowDuration: 2400,
    slowMultiplier: 0.58,
    rangedAttack: Object.freeze({
      type: 'water-bolt',
      range: 620,
      attackStartRange: 445,
      preferredRange: 335,
      projectileSpeed: 680,
      projectileRadius: 22,
      launchDelay: 180,
      recoveryDuration: 180,
      cooldown: 1150,
      targetLeadMs: 180,
      targetLeadMaxDistance: 72,
      slowDuration: 1800,
      slowMultiplier: 0.68,
    }),
  }),
  'old-quarry-giant': Object.freeze({
    type: 'ground-slam',
    radius: 175,
    damage: 96,
    initialDelay: 2400,
    telegraphDuration: 900,
    totalDuration: 1200,
    cooldown: 7000,
    secondary: Object.freeze({
      type: 'boulder-toss',
      damage: 72,
      initialDelay: 3400,
      telegraphDuration: 650,
      recoveryDuration: 380,
      cooldown: 6100,
      activationRange: 760,
      minRange: 105,
      maxTravelDistance: 700,
      projectileSpeed: 430,
      projectileRadius: 42,
      projectileCountMin: 3,
      projectileCountMax: 4,
      projectileSpread: 0.22,
      slowDuration: 3000,
      slowMultiplier: 0.52,
    }),
  }),
});
const FOUR_DIRECTION_ENEMY_SPRITE = Object.freeze({
  directional: true,
  directionRows: Object.freeze({ down: 0, left: 1, right: 2, up: 3 }),
  walkStartColumn: 0,
  attackStartColumn: 4,
});
function enemySpriteConfig(id, boss = false, attackFrameCount = 0, options = {}) {
  return {
    path: `assets/enemies/${id}.png`,
    frameWidth: boss ? 96 : 64,
    frameHeight: boss ? 96 : 64,
    frameCount: 4,
    attackFrameCount,
    attackRow: attackFrameCount > 0 ? 1 : 0,
    attackDuration: 420,
    walkFrameDuration: boss ? 210 : 170,
    drawWidth: boss ? 148 : 76,
    drawHeight: boss ? 148 : 76,
    yOffset: boss ? -112 : -50,
    ...options,
  };
}

function dungeonEnemySpriteConfig(id) {
  return {
    ...enemySpriteConfig(id),
    drawWidth: 94,
    drawHeight: 94,
    yOffset: -66,
  };
}

function dungeonBossSpriteConfig(id) {
  return {
    ...enemySpriteConfig(id, true),
    drawWidth: 166,
    drawHeight: 166,
    yOffset: -126,
  };
}

const ENEMY_SPRITE_CONFIG = {
  wolf: enemySpriteConfig('wolf', false, 4),
  kobold: enemySpriteConfig('kobold'),
  bandit: enemySpriteConfig('bandit'),
  undead: enemySpriteConfig('undead'),
  'restless-dead': enemySpriteConfig('restless-dead'),
  'snow-wolf': enemySpriteConfig('snow-wolf'),
  'frost-trogg': enemySpriteConfig('frost-trogg'),
  'cave-spider': enemySpriteConfig('cave-spider'),
  'grave-rat': enemySpriteConfig('grave-rat'),
  plaguehound: enemySpriteConfig('plaguehound'),
  'forest-sprite': enemySpriteConfig('forest-sprite'),
  'corrupted-treant': enemySpriteConfig('corrupted-treant'),
  nightstalker: enemySpriteConfig('nightstalker'),
  plainstrider: enemySpriteConfig('plainstrider'),
  scorpion: enemySpriteConfig('scorpion'),
  quilboar: enemySpriteConfig('quilboar'),
  'road-bandit': enemySpriteConfig('road-bandit'),
  'dire-wolf': enemySpriteConfig('dire-wolf'),
  'stone-gnoll': enemySpriteConfig('stone-gnoll'),
  'ember-wraith': enemySpriteConfig('ember-wraith'),
  'elder-briarheart': enemySpriteConfig('elder-briarheart', true),
  'granite-matriarch': enemySpriteConfig('granite-matriarch', true),
  'crypt-warden': enemySpriteConfig('crypt-warden', true),
  'moonshade-stag': enemySpriteConfig('moonshade-stag', true),
  'bloodtusk-chief': enemySpriteConfig('bloodtusk-chief', true),
  'varro-the-tollkeeper': enemySpriteConfig('varro-the-tollkeeper', true),
  'thornmaw-alpha': enemySpriteConfig('thornmaw-alpha', true),
  'granite-ogre': enemySpriteConfig('granite-ogre', true),
  'ash-witch': enemySpriteConfig('ash-witch', true),
  'redscar-captain': enemySpriteConfig('redscar-captain', true, 4, {
    ...FOUR_DIRECTION_ENEMY_SPRITE,
    walkFrameDuration: 205,
  }),
  'cave-stalker': dungeonEnemySpriteConfig('cave-stalker'),
  'magma-crawler': dungeonEnemySpriteConfig('magma-crawler'),
  'deep-burrower': dungeonEnemySpriteConfig('deep-burrower'),
  'obsidian-sentinel': dungeonEnemySpriteConfig('obsidian-sentinel'),
  'reedwater-marauder': enemySpriteConfig('reedwater-marauder', false, 4, {
    ...FOUR_DIRECTION_ENEMY_SPRITE,
    frameWidth: 96,
    frameHeight: 96,
    drawWidth: 114,
    drawHeight: 114,
    yOffset: -88,
    walkFrameDuration: 180,
  }),
  'bramblehide-bear': enemySpriteConfig('bramblehide-bear', false, 4),
  'moonbrook-prowler': enemySpriteConfig('moonbrook-prowler', false, 4),
  'redscar-highwayman': enemySpriteConfig('redscar-highwayman', false, 4, {
    ...FOUR_DIRECTION_ENEMY_SPRITE,
    walkFrameDuration: 175,
  }),
  'saltspine-crawler': enemySpriteConfig('saltspine-crawler', false, 4, {
    ...FOUR_DIRECTION_ENEMY_SPRITE,
    frameWidth: 96,
    frameHeight: 96,
    drawWidth: 114,
    drawHeight: 114,
    yOffset: -88,
    walkFrameDuration: 195,
  }),
  'gloomfang-matriarch': dungeonBossSpriteConfig('gloomfang-matriarch'),
  'lava-forged-warden': dungeonBossSpriteConfig('lava-forged-warden'),
  'crystal-horror': dungeonBossSpriteConfig('crystal-horror'),
  'rift-heart': dungeonBossSpriteConfig('rift-heart'),
  'old-quarry-giant': enemySpriteConfig('old-quarry-giant', true, 4, {
    ...FOUR_DIRECTION_ENEMY_SPRITE,
    boulderThrowStartColumn: 8,
    boulderThrowFrameCount: 8,
    drawWidth: 224,
    drawHeight: 224,
    yOffset: -172,
    walkFrameDuration: 255,
  }),
  'tideglass-matriarch': enemySpriteConfig('tideglass-matriarch', true, 8, {
    ...FOUR_DIRECTION_ENEMY_SPRITE,
    frameWidth: 128,
    frameHeight: 128,
    drawWidth: 245,
    drawHeight: 245,
    yOffset: -201,
    walkFrameDuration: 225,
  }),
};

const PET_SPRITE_CONFIG = {
  human: { path: 'assets/pets/human.png', frameWidth: 64, frameHeight: 64, frameCount: 6, drawWidth: 82, drawHeight: 82, yOffset: -42 },
  elf: { path: 'assets/pets/elf.png', frameWidth: 64, frameHeight: 64, frameCount: 6, drawWidth: 82, drawHeight: 82, yOffset: -42 },
  dwarf: { path: 'assets/pets/dwarf.png', frameWidth: 64, frameHeight: 64, frameCount: 6, drawWidth: 82, drawHeight: 82, yOffset: -42 },
  orc: { path: 'assets/pets/orc.png', frameWidth: 64, frameHeight: 64, frameCount: 6, drawWidth: 86, drawHeight: 86, yOffset: -44 },
};

const CUSTOMIZATION = {
  skin: ['#f2c7a4', '#d6a06f', '#f0d6ad', '#74a85a', '#cbd5c0'],
  hair: ['#8b5e34', '#f6d365', '#2f221d', '#d8b4fe', '#d8dee9'],
  robe: ['#4263eb', '#2f9e44', '#e6c55c', '#b42318', '#f8fafc'],
  trim: ['#8be9fd', '#f8fafc', '#facc15', '#64748b', '#c084fc'],
};

const HUMAN_MAGE_CUSTOMIZATION = {
  skin: ['#f2c7a4', '#d6a06f', '#f0d6ad', '#b77952', '#8f5a3c', '#e7b58f', '#c98f6f', '#f4d3b8'],
  eyes: ['#3b2416', '#090d14', '#2563eb', '#15803d', '#7e22ce', '#d97706'],
  hair: ['#8b5e34', '#f6d365', '#2f221d', '#b45309', '#991b1b', '#6d28d9', '#475569', '#d8dee9'],
  hat: ['#4263eb', '#1d4ed8', '#312e81', '#0f766e', '#166534', '#7e22ce', '#9f1239', '#374151'],
  robe: ['#4263eb', '#1d4ed8', '#312e81', '#0f766e', '#166534', '#7e22ce', '#9f1239', '#92400e'],
  trim: ['#8be9fd', '#f8fafc', '#facc15', '#67e8f9', '#a7f3d0', '#c084fc', '#fda4af', '#fdba74'],
  staff: ['#7c4a22', '#5f4329', '#92400e', '#713f12', '#374151', '#3f2a56'],
  crystal: ['#67e8f9', '#38bdf8', '#a7f3d0', '#facc15', '#c084fc', '#f472b6', '#fb7185', '#f8fafc'],
};

const HUMAN_CUSTOMIZATION = {
  skin: HUMAN_MAGE_CUSTOMIZATION.skin,
  eyes: HUMAN_MAGE_CUSTOMIZATION.eyes,
  hair: HUMAN_MAGE_CUSTOMIZATION.hair,
  robe: [...CUSTOMIZATION.robe, '#312e81'],
  trim: CUSTOMIZATION.trim,
  weaponColor: ['#94a3b8', '#d6b25e', '#60a5fa', '#dc2626', '#7c3aed', '#374151'],
};

const FRESH_RACE_CUSTOMIZATION = {
  human: HUMAN_CUSTOMIZATION,
  elf: {
    skin: ['#f0d6ad', '#e8c79a', '#dcb88c', '#f4dfbd', '#cfa77d', '#ead2b4'],
    eyes: ['#2563eb', '#15803d', '#7e22ce', '#0f766e', '#d97706', '#94a3b8'],
    hair: ['#e9d66b', '#f3e5ab', '#8b5e34', '#b45309', '#2f221d', '#d8dee9', '#7e5bef', '#5f7c62'],
    robe: ['#315c47', '#376b75', '#59408c', '#78663a', '#d6d3c4', '#233748'],
    trim: ['#b8e3cf', '#cbd5e1', '#d6b25e', '#7dd3fc', '#c4b5fd', '#94a3b8'],
    weaponColor: ['#cbd5e1', '#d6b25e', '#8dd7c1', '#a5b4fc', '#6b7280', '#334155'],
  },
  dwarf: {
    skin: ['#d6a06f', '#c4895e', '#e0b087', '#b7754d', '#efc59f', '#9f6543'],
    eyes: ['#3b2416', '#15803d', '#2563eb', '#d97706', '#475569', '#090d14'],
    hair: ['#9a4f2f', '#b45309', '#6b351f', '#2f221d', '#d6b25e', '#9ca3af', '#d8dee9', '#7f1d1d'],
    robe: ['#7c2d24', '#854d0e', '#475569', '#3f3f46', '#14532d', '#312e81'],
    trim: ['#d6b25e', '#e2e8f0', '#fb923c', '#94a3b8', '#facc15', '#a16207'],
    weaponColor: ['#64748b', '#d6b25e', '#b45309', '#475569', '#9ca3af', '#27272a'],
  },
  orc: {
    skin: ['#74a85a', '#5f914b', '#86b76a', '#4f7f3f', '#94a85a', '#667a48'],
    eyes: ['#d97706', '#facc15', '#dc2626', '#090d14', '#67e8f9', '#a7f3d0'],
    hair: ['#20251f', '#374151', '#4b2c15', '#6b351f', '#9ca3af', '#d8dee9'],
    robe: ['#365c2d', '#7f1d1d', '#78350f', '#374151', '#3f6212', '#292524'],
    trim: ['#d6b25e', '#e2e8f0', '#f97316', '#a3e635', '#dc2626', '#78716c'],
    weaponColor: ['#64748b', '#b45309', '#78716c', '#7f1d1d', '#365314', '#1c1917'],
  },
  undead: {
    skin: ['#cbd5c0', '#aebdaa', '#d8ddd0', '#9aa79a', '#c6bea9', '#87978c'],
    eyes: ['#67e8f9', '#7e22ce', '#15803d', '#facc15', '#dc2626', '#d8dee9'],
    hair: ['#d8dee9', '#9ca3af', '#475569', '#2f221d', '#6d5b73', '#cbd5c0'],
    robe: ['#3f3f46', '#4c1d95', '#334155', '#3f6212', '#701a75', '#1f2937'],
    trim: ['#a7f3d0', '#c4b5fd', '#94a3b8', '#d8dee9', '#67e8f9', '#a3e635'],
    weaponColor: ['#64748b', '#6b5b53', '#a78bfa', '#475569', '#84cc16', '#292524'],
  },
};

const APPEARANCE_CHOICES = {
  gender: [
    { id: 'male', label: 'Male' },
    { id: 'female', label: 'Female' },
  ],
  hairStyle: [
    { id: 'short', label: 'Short' },
    { id: 'long', label: 'Long' },
    { id: 'hooded', label: 'Hood' },
  ],
  beard: [
    { id: 'none', label: 'None' },
    { id: 'short', label: 'Neat Stubble' },
    { id: 'full', label: 'Trimmed Beard' },
  ],
  outfitVariant: [
    { id: 'classic', label: 'Classic' },
    { id: 'veteran', label: 'Veteran' },
    { id: 'dark', label: 'Dark' },
  ],
  weaponVariant: [
    { id: 'classic', label: 'Classic' },
    { id: 'ornate', label: 'Ornate' },
    { id: 'shadow', label: 'Shadow' },
  ],
  capeStyle: [
    { id: 'none', label: 'None' },
    { id: 'short', label: 'Short' },
    { id: 'long', label: 'Long' },
  ],
};

const HUMAN_FACE_STYLE_CHOICES = [
  { id: 'male-natural', label: 'Natural', gender: 'male' },
  { id: 'male-focused', label: 'Focused', gender: 'male' },
  { id: 'male-scarred', label: 'Scarred', gender: 'male' },
  { id: 'male-cheerful', label: 'Cheerful', gender: 'male' },
  { id: 'female-natural', label: 'Natural', gender: 'female' },
  { id: 'female-focused', label: 'Focused', gender: 'female' },
  { id: 'female-freckled', label: 'Freckled', gender: 'female' },
  { id: 'female-cheerful', label: 'Cheerful', gender: 'female' },
];

const HUMAN_MAGE_APPEARANCE_CHOICES = {
  gender: APPEARANCE_CHOICES.gender,
  faceVariant: HUMAN_FACE_STYLE_CHOICES,
  hairStyle: [
    { id: 'male-cropped', label: 'Cropped', gender: 'male' },
    { id: 'male-windswept', label: 'Side Part', gender: 'male' },
    { id: 'male-tousled', label: 'Layered Crop', gender: 'male' },
    { id: 'male-tied', label: 'Low Tie', gender: 'male' },
    { id: 'female-long', label: 'Long Straight', gender: 'female' },
    { id: 'female-side-bangs', label: 'Side Bangs', gender: 'female' },
    { id: 'female-bun', label: 'High Bun', gender: 'female' },
    { id: 'female-ponytail', label: 'Low Ponytail', gender: 'female' },
  ],
  hatVariant: [
    { id: 'none', label: 'No Hat' },
    { id: 'wanderer', label: 'Wanderer Hat' },
    { id: 'wide', label: 'Broad Brim' },
    { id: 'high-crown', label: 'Scholar Crown' },
    { id: 'starcaller', label: 'Starcaller Hood' },
  ],
  outfitVariant: [
    { id: 'classic', label: 'Apprentice Coat' },
    { id: 'veteran', label: 'Veteran Robe' },
    { id: 'runed', label: 'Runed Scholar' },
    { id: 'dark', label: 'Duskwave Robe' },
  ],
  weaponVariant: [
    { id: 'classic', label: 'Crystal Staff' },
    { id: 'veteran', label: 'Forked Battlestaff' },
    { id: 'runed', label: 'Runic Crook' },
    { id: 'ornate', label: 'Sunfork Staff' },
    { id: 'shadow', label: 'Void Orb Staff' },
  ],
};

const HUMAN_HAIR_STYLE_CHOICES = [
  { id: 'male-cropped', label: 'Cropped', gender: 'male' },
  { id: 'male-windswept', label: 'Side Part', gender: 'male' },
  { id: 'male-tousled', label: 'Layered Crop', gender: 'male' },
  { id: 'male-tied', label: 'Low Tie', gender: 'male' },
  { id: 'female-long', label: 'Long Straight', gender: 'female' },
  { id: 'female-side-bangs', label: 'Side Bangs', gender: 'female' },
  { id: 'female-bun', label: 'High Bun', gender: 'female' },
  { id: 'female-ponytail', label: 'Low Ponytail', gender: 'female' },
];

const FRESH_RACE_FACE_STYLE_CHOICES = {
  human: HUMAN_FACE_STYLE_CHOICES,
  elf: [
    { id: 'male-natural', label: 'Serene', gender: 'male' },
    { id: 'male-focused', label: 'Keen', gender: 'male' },
    { id: 'male-scarred', label: 'Waymarked', gender: 'male' },
    { id: 'male-cheerful', label: 'Bright', gender: 'male' },
    { id: 'female-natural', label: 'Serene', gender: 'female' },
    { id: 'female-focused', label: 'Keen', gender: 'female' },
    { id: 'female-freckled', label: 'Sunmarked', gender: 'female' },
    { id: 'female-cheerful', label: 'Bright', gender: 'female' },
  ],
  dwarf: [
    { id: 'male-natural', label: 'Stout', gender: 'male' },
    { id: 'male-focused', label: 'Stern', gender: 'male' },
    { id: 'male-scarred', label: 'Battle Scar', gender: 'male' },
    { id: 'male-cheerful', label: 'Hearty', gender: 'male' },
    { id: 'female-natural', label: 'Stout', gender: 'female' },
    { id: 'female-focused', label: 'Stern', gender: 'female' },
    { id: 'female-freckled', label: 'Forge Freckles', gender: 'female' },
    { id: 'female-cheerful', label: 'Hearty', gender: 'female' },
  ],
  orc: [
    { id: 'male-natural', label: 'Steady', gender: 'male' },
    { id: 'male-focused', label: 'Fierce', gender: 'male' },
    { id: 'male-scarred', label: 'War Scar', gender: 'male' },
    { id: 'male-cheerful', label: 'Tusked Grin', gender: 'male' },
    { id: 'female-natural', label: 'Steady', gender: 'female' },
    { id: 'female-focused', label: 'Fierce', gender: 'female' },
    { id: 'female-freckled', label: 'War Paint', gender: 'female' },
    { id: 'female-cheerful', label: 'Tusked Grin', gender: 'female' },
  ],
  undead: [
    { id: 'male-natural', label: 'Hollow', gender: 'male' },
    { id: 'male-focused', label: 'Grim', gender: 'male' },
    { id: 'male-scarred', label: 'Cracked', gender: 'male' },
    { id: 'male-cheerful', label: 'Ember Grin', gender: 'male' },
    { id: 'female-natural', label: 'Hollow', gender: 'female' },
    { id: 'female-focused', label: 'Grim', gender: 'female' },
    { id: 'female-freckled', label: 'Mottled', gender: 'female' },
    { id: 'female-cheerful', label: 'Ember Grin', gender: 'female' },
  ],
};

const FRESH_RACE_HAIR_STYLE_CHOICES = {
  human: HUMAN_HAIR_STYLE_CHOICES,
  elf: [
    { id: 'male-cropped', label: 'Court Crop', gender: 'male' },
    { id: 'male-windswept', label: 'Swept Part', gender: 'male' },
    { id: 'male-tousled', label: 'Layered Silken', gender: 'male' },
    { id: 'male-tied', label: 'Bound Length', gender: 'male' },
    { id: 'female-long', label: 'Silken Length', gender: 'female' },
    { id: 'female-side-bangs', label: 'Temple Bangs', gender: 'female' },
    { id: 'female-bun', label: 'Crown Bun', gender: 'female' },
    { id: 'female-ponytail', label: 'Braided Tie', gender: 'female' },
  ],
  dwarf: [
    { id: 'male-cropped', label: 'Forge Crop', gender: 'male' },
    { id: 'male-windswept', label: 'Stone Part', gender: 'male' },
    { id: 'male-tousled', label: 'Rough Layered', gender: 'male' },
    { id: 'male-tied', label: 'Low Braid', gender: 'male' },
    { id: 'female-long', label: 'Shoulder Length', gender: 'female' },
    { id: 'female-side-bangs', label: 'Braided Fringe', gender: 'female' },
    { id: 'female-bun', label: 'Forge Bun', gender: 'female' },
    { id: 'female-ponytail', label: 'Low Braid', gender: 'female' },
  ],
  orc: [
    { id: 'male-cropped', label: 'War Crop', gender: 'male' },
    { id: 'male-windswept', label: 'Swept Mane', gender: 'male' },
    { id: 'male-tousled', label: 'Rough Mane', gender: 'male' },
    { id: 'male-tied', label: 'Bound Mane', gender: 'male' },
    { id: 'female-long', label: 'Long Mane', gender: 'female' },
    { id: 'female-side-bangs', label: 'Side Lock', gender: 'female' },
    { id: 'female-bun', label: 'War Knot', gender: 'female' },
    { id: 'female-ponytail', label: 'Bound Braid', gender: 'female' },
  ],
  undead: [
    { id: 'male-cropped', label: 'Close Shorn', gender: 'male' },
    { id: 'male-windswept', label: 'Faded Part', gender: 'male' },
    { id: 'male-tousled', label: 'Tattered Layer', gender: 'male' },
    { id: 'male-tied', label: 'Grave Tie', gender: 'male' },
    { id: 'female-long', label: 'Faded Length', gender: 'female' },
    { id: 'female-side-bangs', label: 'Tattered Bangs', gender: 'female' },
    { id: 'female-bun', label: 'Grave Bun', gender: 'female' },
    { id: 'female-ponytail', label: 'Faded Tie', gender: 'female' },
  ],
};

const FRESH_RACE_HERITAGE_STYLE_CHOICES = {
  human: [
    { id: 'none', label: 'Unmarked' },
    { id: 'road-freckles', label: 'Road Freckles' },
    { id: 'temple-scar', label: 'Temple Scar' },
    { id: 'guild-mark', label: 'Guild Mark' },
  ],
  elf: [
    { id: 'none', label: 'Unadorned' },
    { id: 'moon-sigil', label: 'Moon Sigil' },
    { id: 'leaf-filigree', label: 'Leaf Filigree' },
    { id: 'star-circlet', label: 'Star Circlet' },
  ],
  dwarf: [
    { id: 'none', label: 'Unmarked' },
    { id: 'forge-smudge', label: 'Forge Smudge' },
    { id: 'clan-rune', label: 'Clan Rune' },
    { id: 'brass-studs', label: 'Brass Studs' },
  ],
  orc: [
    { id: 'none', label: 'Unmarked' },
    { id: 'war-paint', label: 'War Paint' },
    { id: 'fang-stripe', label: 'Fang Stripe' },
    { id: 'bone-studs', label: 'Bone Studs' },
  ],
  undead: [
    { id: 'none', label: 'Unmarked' },
    { id: 'grave-cracks', label: 'Grave Cracks' },
    { id: 'ritual-stitches', label: 'Ritual Stitches' },
    { id: 'spectral-veins', label: 'Spectral Veins' },
  ],
};

const FRESH_RACE_DEFAULT_HERITAGE = {
  human: 'road-freckles',
  elf: 'moon-sigil',
  dwarf: 'clan-rune',
  orc: 'war-paint',
  undead: 'grave-cracks',
};

const HUMAN_CLASS_APPEARANCE_CHOICES = {
  warrior: {
    outfitVariant: [
      { id: 'classic', label: 'Sentinel Plate' },
      { id: 'veteran', label: 'Veteran Bulwark' },
      { id: 'runed', label: 'Runebound Plate' },
      { id: 'dark', label: 'Blackiron Guard' },
    ],
    weaponVariant: [
      { id: 'classic', label: 'Sentinel Sword' },
      { id: 'veteran', label: 'Veteran Blade' },
      { id: 'runed', label: 'Runeblade' },
      { id: 'ornate', label: 'Dawnforged Sword' },
      { id: 'shadow', label: 'Blackiron Sword' },
    ],
  },
  hunter: {
    outfitVariant: [
      { id: 'classic', label: 'Trailwarden Leathers' },
      { id: 'veteran', label: 'Veteran Tracker' },
      { id: 'runed', label: 'Runebough Scout' },
      { id: 'dark', label: 'Nightwood Stalker' },
    ],
    weaponVariant: [
      { id: 'classic', label: 'Longbow' },
      { id: 'veteran', label: 'Ranger Recurve' },
      { id: 'runed', label: 'Runebough Bow' },
      { id: 'ornate', label: 'Sunbranch Recurve' },
      { id: 'shadow', label: 'Nightwood Bow' },
    ],
  },
  paladin: {
    outfitVariant: [
      { id: 'classic', label: 'Dawnshield Plate' },
      { id: 'veteran', label: 'High Templar Plate' },
      { id: 'runed', label: 'Runed Crusader' },
      { id: 'dark', label: 'Ashen Vindicator' },
    ],
    weaponVariant: [
      { id: 'classic', label: 'Dawnforged Sword' },
      { id: 'veteran', label: 'Templar Blade' },
      { id: 'runed', label: 'Runed Crusader Sword' },
      { id: 'ornate', label: 'Sunforged Sword' },
      { id: 'shadow', label: 'Ashen Vindicator Blade' },
    ],
  },
  priest: {
    outfitVariant: [
      { id: 'classic', label: 'Acolyte Vestments' },
      { id: 'veteran', label: 'High Cleric Mantle' },
      { id: 'runed', label: 'Runed Vestments' },
      { id: 'dark', label: 'Moonlit Vestments' },
    ],
    weaponVariant: [
      { id: 'classic', label: 'Pilgrim Staff' },
      { id: 'veteran', label: 'Shepherd Crook' },
      { id: 'runed', label: 'Runic Reliquary' },
      { id: 'ornate', label: 'Reliquary Staff' },
      { id: 'shadow', label: 'Moonlit Staff' },
    ],
  },
  rogue: {
    outfitVariant: [
      { id: 'classic', label: 'Cutpurse Leathers' },
      { id: 'veteran', label: 'Veteran Nightblade' },
      { id: 'runed', label: 'Runemark Leathers' },
      { id: 'dark', label: 'Shadowmantle' },
    ],
    weaponVariant: [
      { id: 'classic', label: 'Twin Knives' },
      { id: 'veteran', label: 'Ranger Kukri' },
      { id: 'runed', label: 'Runed Stilettos' },
      { id: 'ornate', label: 'Moonsteel Blades' },
      { id: 'shadow', label: 'Shadow Hooks' },
    ],
  },
};

function makeFreshClassAppearanceChoices(outfitNames, weaponNames) {
  const outfitIds = ['classic', 'veteran', 'runed', 'dark'];
  const weaponIds = ['classic', 'veteran', 'runed', 'ornate', 'shadow'];
  return {
    outfitVariant: outfitIds.map((id, index) => ({ id, label: outfitNames[index] })),
    weaponVariant: weaponIds.map((id, index) => ({ id, label: weaponNames[index] })),
  };
}

const FRESH_RACE_CLASS_APPEARANCE_CHOICES = {
  human: {
    mage: HUMAN_MAGE_APPEARANCE_CHOICES,
    ...HUMAN_CLASS_APPEARANCE_CHOICES,
  },
  elf: {
    mage: makeFreshClassAppearanceChoices(
      ['Moonweave Coat', 'Starbough Robe', 'Moonsigil Regalia', 'Gloamweave Robe'],
      ['Moonbranch Staff', 'Starwood Battlestaff', 'Moonsigil Crook', 'Sunleaf Staff', 'Gloamglass Staff'],
    ),
    hunter: makeFreshClassAppearanceChoices(
      ['Verdant Wayfarer', 'Silverleaf Ranger', 'Moonsigil Stalker', 'Gloamleaf Leathers'],
      ['Ashwood Recurve', 'Silverleaf Longbow', 'Moonstring Bow', 'Sunbranch Recurve', 'Gloamthorn Bow'],
    ),
    priest: makeFreshClassAppearanceChoices(
      ['Moonwell Vestments', 'High Warden Mantle', 'Moonsigil Vestments', 'Gloamveil Robes'],
      ['Moonwell Crook', 'Silver Reliquary', 'Moonsigil Staff', 'Sunwell Staff', 'Gloamstaff'],
    ),
    rogue: makeFreshClassAppearanceChoices(
      ['Shadowleaf Leathers', 'Silverblade Harness', 'Moonsigil Leathers', 'Gloamrunner Garb'],
      ['Leaf Knives', 'Silverleaf Kukri', 'Moonrune Blades', 'Sunsteel Blades', 'Gloam Hooks'],
    ),
  },
  dwarf: {
    paladin: makeFreshClassAppearanceChoices(
      ['Forgeguard Plate', 'Oathsteel Bulwark', 'Runeforge Plate', 'Deepiron Guard'],
      ['Hammered Sword', 'Oathsteel Blade', 'Runeblade', 'Sunforged Sword', 'Deepiron Sword'],
    ),
    warrior: makeFreshClassAppearanceChoices(
      ['Hearthguard Plate', 'Clan Champion Plate', 'Runeforge Harness', 'Blackiron Guard'],
      ['Forge Sword', 'Clan Blade', 'Rune Cleaver', 'Gilded Forgeblade', 'Blackiron Sword'],
    ),
    hunter: makeFreshClassAppearanceChoices(
      ['Stonepath Leathers', 'Deepdelver Scout', 'Runetrack Harness', 'Nightmine Stalker'],
      ['Crossgrain Shortbow', 'Deepwood Recurve', 'Runewood Bow', 'Goldbranch Bow', 'Blackwood Bow'],
    ),
    priest: makeFreshClassAppearanceChoices(
      ['Anvil Shrine Robes', 'High Thane Mantle', 'Runesmith Vestments', 'Deep Shrine Robes'],
      ['Runestone Staff', 'Anvil Crook', 'Rune Reliquary', 'Goldspire Staff', 'Deepstone Staff'],
    ),
    rogue: makeFreshClassAppearanceChoices(
      ['Deeproad Leathers', 'Mine Scout Harness', 'Runecut Leathers', 'Nightdelver Garb'],
      ['Mine Knives', 'Forge Kukri', 'Rune Picks', 'Goldsteel Blades', 'Blackiron Hooks'],
    ),
  },
  orc: {
    warrior: makeFreshClassAppearanceChoices(
      ['Warhide Harness', 'Clan Champion Plate', 'Bloodrune Armor', 'Nightfang Guard'],
      ['Iron Cleaver', 'Clan Blade', 'Bloodrune Sword', 'Sunfang Blade', 'Nightfang Cleaver'],
    ),
    hunter: makeFreshClassAppearanceChoices(
      ['Beaststalker Hide', 'Warcamp Tracker', 'Bloodrune Hunter', 'Nightfang Stalker'],
      ['Hornbow', 'War Recurve', 'Bloodstring Bow', 'Sunbone Bow', 'Nightfang Bow'],
    ),
    rogue: makeFreshClassAppearanceChoices(
      ['Raid Leathers', 'Clan Shadow Garb', 'Bloodrune Harness', 'Nightfang Leathers'],
      ['Raid Knives', 'Hooked Kukri', 'Bloodrune Blades', 'Goldfang Blades', 'Nightfang Hooks'],
    ),
  },
  undead: {
    mage: makeFreshClassAppearanceChoices(
      ['Graveweave Coat', 'Crypt Scholar Robe', 'Deathsigil Regalia', 'Nightshroud Robe'],
      ['Bone Staff', 'Crypt Spire', 'Deathsigil Crook', 'Soul Lantern Staff', 'Graveglass Staff'],
    ),
    warrior: makeFreshClassAppearanceChoices(
      ['Cryptguard Plate', 'Deathwatch Armor', 'Graverune Harness', 'Night Crypt Guard'],
      ['Rusted Sword', 'Deathwatch Blade', 'Graverune Sword', 'Gilded Relic Blade', 'Nightbone Sword'],
    ),
    priest: makeFreshClassAppearanceChoices(
      ['Pallid Acolyte Robes', 'Sepulcher Mantle', 'Cryptsigil Vestments', 'Veil Robes'],
      ['Grave Crook', 'Sepulcher Staff', 'Cryptsigil Staff', 'Soul Reliquary', 'Veilstaff'],
    ),
    rogue: makeFreshClassAppearanceChoices(
      ['Gravecut Leathers', 'Deathstalker Harness', 'Cryptsigil Garb', 'Nightveil Leathers'],
      ['Bone Knives', 'Rust Kukri', 'Cryptfang Blades', 'Soulsteel Blades', 'Nightbone Hooks'],
    ),
  },
};

const TREES = [
  [260, 240], [430, 380], [620, 250], [940, 440], [1180, 280], [1450, 520],
  [1760, 330], [2040, 570], [2380, 410], [2710, 650], [3090, 360],
  [360, 920], [720, 760], [1010, 1050], [1390, 900], [1680, 1120],
  [2090, 890], [2460, 1010], [2860, 910], [3240, 1180],
  [520, 1540], [860, 1320], [1230, 1690], [1560, 1450], [1930, 1600],
  [2320, 1370], [2680, 1700], [3120, 1490],
  [390, 2050], [760, 1900], [1130, 2180], [1510, 1990], [1880, 2110],
  [2260, 1920], [2630, 2200], [3070, 2020], [3370, 2140],
];

const ROCKS = [
  [780, 520], [1320, 650], [2180, 260], [3010, 780], [460, 1280],
  [1120, 1370], [1810, 760], [2530, 1320], [3360, 980], [940, 2040],
  [2110, 2180], [2890, 1880],
];

const NPCS = [
  { x: 560, y: 590, name: 'Lina', color: '#f97316' },
  { x: 1710, y: 1340, name: 'Marek', color: '#06b6d4' },
  { x: 2920, y: 1540, name: 'Sera', color: '#a855f7' },
];

export {
  PLAYER,
  ENEMY,
  SAVE_KEY,
  FRIENDS_KEY,
  REMEMBER_LOGIN_KEY,
  ADMIN_EMAILS,
  MAX_LEVEL,
  ENEMY_XP,
  BOSS_XP,
  BOSS_SPAWN_MIN,
  BOSS_SPAWN_MAX,
  BOSS_RESPAWN_DELAY,
  COLYSEUS_INPUT_MS,
  COLYSEUS_RECONNECT_MS,
  COLYSEUS_MAX_RECONNECT_ATTEMPTS,
  REMOTE_PLAYER_LEAD_MS,
  REMOTE_PLAYER_SMOOTHING,
  REMOTE_PLAYER_SNAP_DISTANCE,
  AUTO_ATTACK_BASE_COOLDOWN_MS,
  AUTO_ATTACK_MIN_COOLDOWN_MS,
  AUTO_ATTACK_MAX_COOLDOWN_MS,
  CHANNEL_MAX_DURATION_MS,
  BASE_STATS,
  STAT_DESCRIPTIONS,
  INVENTORY_CAPACITY,
  RECALL_ITEM_ID,
  RECALL_CAST_MS,
  RECALL_ITEM,
  STARTER_HEALTH_POTION_ID,
  POTION_COOLDOWN_MS,
  BANK_CAPACITY,
  AUCTION_LISTINGS_KEY,
  STARTER_HEALTH_POTION,
  POTION_TEMPLATES,
  CITY_VENDOR_STOCK,
  PROFESSIONS,
  PROFESSION_BY_ID,
  ABILITY_BAR_SLOTS,
  TALENT_UNLOCK_LEVEL,
  HUNTER_PET,
  EQUIPMENT_SLOTS,
  STAT_GROWTH,
  ABILITY_MANA_COST,
  ABILITY_COOLDOWNS,
  getAbilityTickRateMs,
  shouldEffectFollowCaster,
  TALENTS,
  TALENT_BRANCHES,
  TALENT_NODES,
  SPEC_FINAL_ABILITY_LEVEL,
  SPEC_FINAL_ABILITIES,
  BOSS_LOOT,
  SHOPKEEPER,
  RACES,
  CLASSES,
  CLASS_NAME_POOLS,
  CHARACTER_SPRITE_SIZE,
  CHARACTER_SPRITE_DRAW_SIZE,
  CHARACTER_SPRITE_COLUMNS,
  CHARACTER_SPRITE_EXPECTED_WIDTH,
  CHARACTER_SPRITE_EXPECTED_HEIGHT,
  CHARACTER_SPRITE_EIGHT_DIRECTION_HEIGHT,
  HUMAN_CHARACTER_SPRITE_COLUMNS,
  HUMAN_CHARACTER_SPRITE_SIZE,
  HUMAN_CHARACTER_SPRITE_EXPECTED_WIDTH,
  HUMAN_CHARACTER_SPRITE_EXPECTED_HEIGHT,
  HUMAN_CHARACTER_WALK_COLUMNS,
  HUMAN_CHARACTER_ATTACK_COLUMNS,
  CHARACTER_SPRITE_VERSION,
  CHARACTER_SPRITE_VARIANTS,
  CHARACTER_SPRITE_ROWS,
  CHARACTER_SPRITE_ROWS_8,
  CHARACTER_SPRITES,
  CHARACTER_SPRITE_LOADS,
  CHARACTER_TINTED_SPRITES,
  CHARACTER_SPRITE_SOURCE_PALETTES,
  CHARACTER_LAYER_ORDER,
  CHARACTER_LAYER_IMAGES,
  CHARACTER_LAYER_LOADS,
  ENEMY_SPRITES,
  ENEMY_SPRITE_LOADS,
  PET_SPRITES,
  PET_SPRITE_LOADS,
  PET_SPRITE_VERSION,
  ENEMY_SPRITE_VERSION,
  SHOW_MAP_ENEMY_DOTS,
  MAP_CANVAS_REDRAW_MS,
  WORLD_BOSS_MECHANICS,
  enemySpriteConfig,
  dungeonEnemySpriteConfig,
  dungeonBossSpriteConfig,
  ENEMY_SPRITE_CONFIG,
  PET_SPRITE_CONFIG,
  CUSTOMIZATION,
  HUMAN_CUSTOMIZATION,
  HUMAN_MAGE_CUSTOMIZATION,
  FRESH_RACE_CUSTOMIZATION,
  APPEARANCE_CHOICES,
  HUMAN_FACE_STYLE_CHOICES,
  FRESH_RACE_FACE_STYLE_CHOICES,
  HUMAN_MAGE_APPEARANCE_CHOICES,
  HUMAN_HAIR_STYLE_CHOICES,
  FRESH_RACE_HAIR_STYLE_CHOICES,
  FRESH_RACE_HERITAGE_STYLE_CHOICES,
  FRESH_RACE_DEFAULT_HERITAGE,
  HUMAN_CLASS_APPEARANCE_CHOICES,
  FRESH_RACE_CLASS_APPEARANCE_CHOICES,
  TREES,
  ROCKS,
  NPCS,
};
