import {
  Crosshair,
  Hammer,
  HeartPulse,
  Leaf,
  Shield,
  Skull,
  Sword,
  User,
  Wand2,
} from 'lucide-react';
import { safeNumber } from './math';

const PLAYER = {
  radius: 18,
  speed: 260,
  manaRegen: 7,
  hpRegen: 5,
  outOfCombatDelay: 5000,
};

const ENEMY = {
  maxCount: 12,
  radius: 17,
  speed: 105,
  spawnEvery: 1800,
  wanderSpeed: 48,
};

const SAVE_KEY = 'mmo-project.characters.v1';
const FRIENDS_KEY = 'mmo-project.friends.v1';
const REMEMBER_LOGIN_KEY = 'mmo-project.remember-login.v1';
const ADMIN_EMAILS = new Set(['romvariszabi03@gmail.com']);
const MAX_LEVEL = 30;
const ENEMY_XP = 35;
const BOSS_XP = 180;
const BOSS_SPAWN_MIN = 18000;
const BOSS_SPAWN_MAX = 34000;
const BOSS_RESPAWN_DELAY = 60000;
const COLYSEUS_INPUT_MS = 50;
const COLYSEUS_RECONNECT_MS = 1800;
const COLYSEUS_MAX_RECONNECT_ATTEMPTS = 3;
const REMOTE_PLAYER_LEAD_MS = 90;
const REMOTE_PLAYER_SMOOTHING = 15;
const REMOTE_PLAYER_SNAP_DISTANCE = 360;
const AUTO_ATTACK_BASE_COOLDOWN_MS = 900;
const AUTO_ATTACK_MIN_COOLDOWN_MS = 360;
const AUTO_ATTACK_MAX_COOLDOWN_MS = 1600;
const CHANNEL_MAX_DURATION_MS = 600000;
const BASE_STATS = {
  health: 100,
  mana: 60,
  strength: 5,
  agility: 5,
  intellect: 5,
  attackSpeed: 1,
};

const STAT_DESCRIPTIONS = {
  health: 'Maximum health. If it reaches 0, you die.',
  mana: 'Caster resource used by magical and ranged abilities.',
  fury: 'Warrior resource generated by attacks and spent on abilities.',
  energy: 'Rogue resource that regenerates quickly and fuels abilities.',
  strength: 'Increases melee and physical damage.',
  agility: 'Increases bow, dagger and attack speed scaling.',
  intellect: 'Increases spell damage, healing and mana scaling.',
  attackSpeed: 'Multiplies auto attack speed. Higher is faster.',
};

const INVENTORY_CAPACITY = 28;
const RECALL_ITEM_ID = 'account-recall-stone';
const RECALL_CAST_MS = 5000;
const RECALL_ITEM = {
  id: RECALL_ITEM_ID,
  name: 'Recall Stone',
  rarity: 'Rare',
  type: 'usable',
  action: 'recall',
  slot: null,
  stats: {},
  nonDestroyable: true,
  soulbound: true,
  foundAt: 'system',
  description: 'Use: after 5 seconds, teleports you to the nearest respawn point.',
};
const STARTER_HEALTH_POTION_ID = 'starter-health-potion-stack';
const POTION_COOLDOWN_MS = 15000;
const BANK_CAPACITY = 60;
const AUCTION_LISTINGS_KEY = 'mmo-auction-house-listings-v1';
const STARTER_HEALTH_POTION = {
  id: STARTER_HEALTH_POTION_ID,
  name: 'Lesser Healing Potion',
  rarity: 'Common',
  type: 'potion',
  potionType: 'health',
  action: 'heal',
  slot: null,
  stats: {},
  quantity: 8,
  maxStack: 20,
  stackable: true,
  healAmount: 145,
  foundAt: 'system',
  description: 'Restores 145 health. Assign as main potion and press Q to use.',
};
const POTION_TEMPLATES = {
  lesser_healing_potion: {
    name: 'Lesser Healing Potion',
    rarity: 'Common',
    type: 'potion',
    potionType: 'health',
    action: 'heal',
    quantity: 1,
    maxStack: 20,
    stackable: true,
    healAmount: 145,
    price: 5,
    description: 'Restores 145 health.',
  },
  healing_potion: {
    name: 'Healing Potion',
    rarity: 'Uncommon',
    type: 'potion',
    potionType: 'health',
    action: 'heal',
    quantity: 1,
    maxStack: 20,
    stackable: true,
    healAmount: 285,
    price: 14,
    description: 'Restores 285 health.',
  },
  mana_potion: {
    name: 'Mana Potion',
    rarity: 'Uncommon',
    type: 'potion',
    potionType: 'mana',
    action: 'restoreMana',
    quantity: 1,
    maxStack: 20,
    stackable: true,
    manaAmount: 180,
    price: 12,
    description: 'Restores 180 mana.',
  },
};
const CITY_VENDOR_STOCK = {
  general: [
    { id: 'lesser_healing_potion', item: POTION_TEMPLATES.lesser_healing_potion },
    { id: 'healing_potion', item: POTION_TEMPLATES.healing_potion },
  ],
  alchemy: [
    { id: 'lesser_healing_potion', item: POTION_TEMPLATES.lesser_healing_potion },
    { id: 'healing_potion', item: POTION_TEMPLATES.healing_potion },
    { id: 'mana_potion', item: POTION_TEMPLATES.mana_potion },
  ],
  weaponsmith: [
    { id: 'asterfall_iron_sword', item: { name: 'Asterfall Iron Sword', rarity: 'Uncommon', type: 'weapon', slot: 'weapon', stats: { strength: 5, attackSpeed: 0.03 }, price: 32 } },
    { id: 'willow_shortbow', item: { name: 'Willow Shortbow', rarity: 'Uncommon', type: 'weapon', slot: 'weapon', stats: { agility: 5, attackSpeed: 0.04 }, price: 32 } },
    { id: 'apprentice_wand', item: { name: 'Apprentice Wand', rarity: 'Uncommon', type: 'weapon', slot: 'weapon', stats: { intellect: 5, mana: 18 }, price: 34 } },
  ],
  armorer: [
    { id: 'guard_chain_chest', item: { name: 'Guard Chain Chest', rarity: 'Uncommon', type: 'armor', slot: 'chest', stats: { health: 38, strength: 2 }, price: 36 } },
    { id: 'travelers_boots', item: { name: "Traveler's Boots", rarity: 'Uncommon', type: 'armor', slot: 'boots', stats: { health: 18, agility: 2 }, price: 22 } },
  ],
  arcane: [
    { id: 'moonlit_offhand', item: { name: 'Moonlit Offhand', rarity: 'Uncommon', type: 'offhand', slot: 'offhand', stats: { intellect: 4, mana: 30 }, price: 30 } },
    { id: 'adept_ring', item: { name: 'Adept Ring', rarity: 'Rare', type: 'ring', slot: 'ring', stats: { intellect: 4, mana: 22 }, price: 52 } },
  ],
  stable: [
    { id: 'trail_rations', item: { name: 'Trail Rations', rarity: 'Common', type: 'potion', potionType: 'health', action: 'heal', quantity: 1, maxStack: 20, stackable: true, healAmount: 90, price: 3, description: 'A cheap field recovery item.' } },
  ],
};
const PROFESSIONS = [
  { id: 'fishing', displayName: 'Fishing', description: 'Catch fish and water materials near rivers, lakes, and docks.' },
  { id: 'mining', displayName: 'Mining', description: 'Gather ore from rocky highlands, caves, and mountain routes.' },
  { id: 'leatherworking', displayName: 'Leatherworking', description: 'Turn hides into leather armor and utility gear.' },
  { id: 'tailoring', displayName: 'Tailoring', description: 'Craft cloth armor, bags, and caster-focused gear.' },
  { id: 'blacksmithing', displayName: 'Blacksmithing', description: 'Forge weapons, plate armor, and repair supplies.' },
];
const PROFESSION_BY_ID = Object.fromEntries(PROFESSIONS.map((profession) => [profession.id, profession]));
const ABILITY_BAR_SLOTS = 5;
const TALENT_UNLOCK_LEVEL = 10;

const HUNTER_PET = {
  followDistance: 58,
  leashDistance: 320,
  speed: 240,
  radius: 16,
  attackRange: 58,
  attackCooldown: 880,
  damage: 58,
};

const EQUIPMENT_SLOTS = [
  { id: 'head', label: 'Head' },
  { id: 'chest', label: 'Chest' },
  { id: 'legs', label: 'Legs' },
  { id: 'boots', label: 'Boots' },
  { id: 'weapon', label: 'Weapon' },
  { id: 'offhand', label: 'Offhand' },
  { id: 'ring', label: 'Ring' },
  { id: 'trinket', label: 'Trinket' },
];

const STAT_GROWTH = {
  mage: { health: 8, mana: 16, strength: 1, agility: 1, intellect: 4, attackSpeed: 0.01 },
  hunter: { health: 11, mana: 8, strength: 2, agility: 4, intellect: 1, attackSpeed: 0.035 },
  paladin: { health: 14, mana: 10, strength: 3, agility: 1, intellect: 2, attackSpeed: 0.02 },
  warrior: { health: 16, mana: 4, strength: 4, agility: 2, intellect: 0, attackSpeed: 0.025 },
  priest: { health: 9, mana: 15, strength: 1, agility: 1, intellect: 4, attackSpeed: 0.015 },
  rogue: { health: 10, mana: 8, strength: 2, agility: 5, intellect: 1, attackSpeed: 0.055 },
};

const ABILITY_MANA_COST = {
  1: 12,
  2: 18,
  3: 26,
  4: 36,
  5: 48,
  6: 62,
};

const ABILITY_COOLDOWNS = {
  strike: 900,
  cleave: 1200,
  shot: 1100,
  bolt: 1150,
  chain: 5200,
  aura: 6500,
  ground: 9000,
  hot: 2500,
  healGround: 8500,
  buff: 12000,
  nova: 2600,
  trap: 3200,
  shield: 4200,
  shout: 3600,
  heal: 1600,
  channel: 4800,
};

function getAbilityTickRateMs(ability) {
  if (!ability) return 500;
  const fallback = ability.type === 'ground' || ability.type === 'healGround' || ability.type === 'hot'
    ? 1000
    : 500;
  return Math.max(80, safeNumber(ability.tickRate, fallback));
}

function shouldEffectFollowCaster(ability) {
  if (!ability) return false;
  if (ability.followCaster) return true;
  if (ability.type === 'shield') return true;
  return ability.type === 'buff'
    && Boolean(
      ability.absorb
      || ability.invulnerable
      || ability.invisibility
      || ability.damageReduction
      || ability.regenPerSecond
      || ability.autoDamageMultiplier
      || ability.strikeDamageMultiplier
      || ability.poisonWindow
      || ability.noEnergyCost
      || ability.noManaCost
      || ability.cooldownMultiplier
      || ability.stealthDamageMultiplier
      || ability.manaRegenPerSecond
      || ability.furyRegenPerSecond
      || ability.attackSpeedMultiplier
      || ability.petAttackSpeedMultiplier
      || ability.burnWindow
      || ability.rootSelf
      || ability.maxHealthMultiplier
      || ability.autoCombatBolt
      || ability.healingMultiplier
      || ability.damageMultiplier
      || ability.leechPercent,
    );
}

const TALENTS = {
  paladin: {
    unlockLevel: 10,
    specs: {
      verdict: {
        name: 'Oath of the Verdict',
        role: 'Damage',
        description: 'Holy strikes become sharper and faster.',
        bonuses: { strength: 5, intellect: 2, mana: 15 },
        abilities: [
          { key: '1', level: 10, name: 'Crusader Swing', type: 'strike', color: '#fde68a', damage: 96, manaCost: 28, cooldown: 950 },
          {
            key: '2',
            level: 10,
            name: 'Hammerstorm',
            type: 'aura',
            color: '#facc15',
            damage: 34,
            manaCost: 42,
            duration: 2000,
            tickRate: 500,
            radius: 116,
            followCaster: true,
            cooldown: 6500,
          },
          {
            key: '3',
            level: 12,
            name: 'Consecrated Field',
            type: 'ground',
            color: '#fef3c7',
            damage: 46,
            manaCost: 58,
            duration: 5000,
            tickRate: 1000,
            radius: 112,
            groundAtCursor: true,
            cooldown: 9000,
          },
          {
            key: '4',
            level: 16,
            name: "Zealot's Edge",
            type: 'buff',
            color: '#fff7ad',
            manaCost: 36,
            duration: 7000,
            autoDamageMultiplier: 1.65,
            strikeDamageMultiplier: 1.65,
            cooldown: 14000,
          },
        ],
      },
      aegis: {
        name: 'Aegis of Dawn',
        role: 'Tank',
        description: 'You constantly draw enemy focus while fighting.',
        bonuses: { health: 55, strength: 2, intellect: 2, mana: 20 },
        passive: 'Radiant Taunt',
        abilities: [
          { key: '1', level: 10, name: 'Shield Slam', type: 'strike', color: '#bfdbfe', damage: 68, manaCost: 22, cooldown: 950 },
          {
            key: '2',
            level: 10,
            name: "Avenger's Shield",
            type: 'chain',
            color: '#fef08a',
            damage: 56,
            manaCost: 34,
            range: 430,
            maxTargets: 5,
            chainRange: 230,
            segmentMs: 220,
            combatOnly: true,
            cooldown: 6800,
          },
          {
            key: '3',
            level: 12,
            name: 'Guardian Hammers',
            type: 'aura',
            color: '#fde68a',
            damage: 24,
            manaCost: 46,
            duration: 5000,
            tickRate: 500,
            radius: 112,
            followCaster: true,
            cooldown: 10500,
          },
          {
            key: '4',
            level: 16,
            name: 'Bastion Renewal',
            type: 'buff',
            color: '#e0f2fe',
            manaCost: 42,
            duration: 7000,
            damageReduction: 0.45,
            regenPerSecond: 18,
            cooldown: 16000,
          },
        ],
      },
    },
  },
  warrior: {
    unlockLevel: 10,
    specs: {
      berserker: {
        name: 'Blood Fury',
        role: 'Damage',
        description: 'Builds fury through aggressive slashes, then spends it on wide melee pressure.',
        bonuses: { strength: 6, agility: 2, health: 18, fury: 20 },
        abilities: [
          { key: '1', level: 10, name: 'Slash', type: 'strike', color: '#f97316', damage: 82, furyCost: 0, furyGain: 10, cooldown: 850, range: 96, width: 48 },
          { key: '2', level: 10, name: 'Sweeping Slash', type: 'cleave', color: '#fb923c', damage: 92, furyCost: 22, cooldown: 2600, range: 145, arc: 0.95, width: 70 },
          { key: '3', level: 12, name: 'Double Slash', type: 'cleave', color: '#fecaca', damage: 56, furyCost: 28, cooldown: 5200, range: 120, arc: 0.75, width: 64, multiStrike: 2 },
          { key: '4', level: 16, name: 'Bladestorm', type: 'aura', color: '#ef4444', damage: 42, furyCost: 38, duration: 4000, tickRate: 500, radius: 126, followCaster: true, cooldown: 14000 },
        ],
      },
      ironward: {
        name: 'Iron Ward',
        role: 'Tank',
        description: 'Generates fury with shield attacks and converts it into mitigation and self-healing.',
        bonuses: { health: 70, strength: 4, agility: 1, fury: 15 },
        passive: 'Shield Discipline',
        abilities: [
          { key: '1', level: 10, name: 'Shield Slam', type: 'strike', color: '#cbd5e1', damage: 70, furyCost: 0, furyGain: 12, cooldown: 900, range: 90, width: 48 },
          { key: '2', level: 10, name: 'Shield Sweep', type: 'nova', color: '#94a3b8', damage: 62, furyCost: 24, radius: 112, cooldown: 5200 },
          { key: '3', level: 12, name: 'Guard Wall', type: 'buff', color: '#e5e7eb', furyCost: 32, duration: 6000, absorb: 95, damageReduction: 0.35, followCaster: true, cooldown: 15000 },
          { key: '4', level: 16, name: 'Vanguard Cleave', type: 'cleave', color: '#d1d5db', damage: 86, furyCost: 34, range: 130, arc: 0.9, selfHealPercent: 0.28, cooldown: 7600 },
        ],
      },
    },
  },
  hunter: {
    unlockLevel: 10,
    specs: {
      beastmaster: {
        name: 'Sharpshooter',
        role: 'Damage',
        description: 'Long-range bow pressure with multishot, rapid fire, and armor-piercing mark shots.',
        bonuses: { agility: 7, strength: 1, mana: 20, attackSpeed: 0.08 },
        passive: 'Loyal Pet',
        abilities: [
          { key: '1', level: 10, name: 'Steady Shot', type: 'shot', color: '#fde68a', damage: 72, manaCost: 18, range: 590, width: 22, cooldown: 850 },
          { key: '2', level: 10, name: 'Multishot', type: 'cleave', color: '#bef264', damage: 74, manaCost: 34, range: 420, arc: 0.55, width: 96, cooldown: 5200 },
          { key: '3', level: 12, name: 'Rapid Fire', type: 'channel', color: '#facc15', damage: 28, manaCost: 10, duration: 3600, tickRate: 300, range: 590, width: 28, cooldown: 10500, followCaster: true },
          { key: '4', level: 16, name: 'Piercing Shot', type: 'shot', color: '#fef08a', damage: 132, manaCost: 54, range: 660, width: 42, pierce: true, cooldown: 11000 },
        ],
      },
      survival: {
        name: 'Wildstalker',
        role: 'Damage',
        description: 'Poison arrows, traps, arrow rain, and pet bleed burst windows.',
        bonuses: { agility: 5, health: 28, mana: 18, attackSpeed: 0.05 },
        passive: 'Loyal Pet',
        abilities: [
          { key: '1', level: 10, name: 'Barbed Shot', type: 'shot', color: '#86efac', damage: 68, manaCost: 18, range: 560, width: 22, cooldown: 900 },
          { key: '2', level: 10, name: 'Poison Arrow', type: 'shot', color: '#65a30d', damage: 54, manaCost: 32, range: 570, width: 24, applyPoison: true, poisonDamage: 9, poisonDuration: 5000, poisonTickRate: 1000, cooldown: 4800 },
          { key: '3', level: 12, name: 'Explosive Trap', type: 'trap', color: '#fb923c', damage: 34, manaCost: 42, duration: 15000, tickRate: 160, radius: 104, trapOffset: 120, slowDuration: 3000, slowMultiplier: 0.55, cooldown: 9000 },
          { key: '4', level: 16, name: 'Arrow Rain', type: 'ground', color: '#fde047', damage: 34, manaCost: 58, duration: 4000, tickRate: 500, radius: 132, groundAtCursor: true, cooldown: 11500 },
        ],
      },
    },
  },
  mage: {
    unlockLevel: 10,
    specs: {
      frost: {
        name: 'Frostbinder',
        role: 'Damage',
        description: 'Frost spells apply Cold for 3 seconds, slowing enemies before shattering them.',
        bonuses: { intellect: 6, mana: 26, health: 12 },
        passive: 'Cold Snap',
        abilities: [
          { key: '1', level: 10, name: 'Frost Bolt', type: 'bolt', color: '#7dd3fc', damage: 76, manaCost: 22, range: 560, width: 24, cooldown: 950, applyCold: true, slowDuration: 3000, slowMultiplier: 0.55 },
          { key: '2', level: 10, name: 'Frozen Circle', type: 'ground', color: '#bae6fd', damage: 22, manaCost: 46, duration: 520, tickRate: 520, radius: 118, groundAtCursor: true, freezeDuration: 2200, cooldown: 11000 },
          { key: '3', level: 12, name: 'Hailstorm', type: 'ground', color: '#e0f2fe', damage: 36, manaCost: 56, duration: 4000, tickRate: 500, radius: 126, groundAtCursor: true, cooldown: 12000 },
          { key: '4', level: 16, name: 'Shatter Spike', type: 'bolt', color: '#cffafe', damage: 54, manaCost: 34, range: 570, width: 24, skipCold: true, bonusVsControlledMultiplier: 2.15, cooldown: 4200 },
        ],
      },
      arcane: {
        name: 'Firecaller',
        role: 'Damage',
        description: 'Fire spells burn enemies and build toward inferno burst windows.',
        bonuses: { intellect: 7, mana: 22, attackSpeed: 0.04 },
        abilities: [
          { key: '1', level: 10, name: 'Fire Bolt', type: 'bolt', color: '#fb923c', damage: 82, manaCost: 24, range: 560, width: 24, cooldown: 950 },
          { key: '2', level: 10, name: 'Fireball', type: 'shot', color: '#ef4444', damage: 80, manaCost: 42, range: 590, width: 34, pierce: true, applyBurn: true, burnDamage: 12, burnDuration: 5000, burnTickRate: 1000, cooldown: 6200 },
          { key: '3', level: 12, name: 'Flame Wave', type: 'aura', color: '#f97316', damage: 46, manaCost: 52, duration: 4000, tickRate: 1000, radius: 118, followCaster: true, cooldown: 11000 },
          { key: '4', level: 16, name: 'Burning Ground', type: 'ground', color: '#fb7185', damage: 38, manaCost: 58, duration: 4000, tickRate: 500, radius: 122, groundAtCursor: true, applyBurn: true, burnDamage: 10, burnDuration: 4500, burnTickRate: 1000, cooldown: 12000 },
        ],
      },
    },
  },
  priest: {
    unlockLevel: 10,
    specs: {
      void: {
        name: 'Enter the Void',
        role: 'Damage',
        description: 'Void magic channels, curses, and turns mana into purple pressure.',
        bonuses: { intellect: 7, mana: 26, attackSpeed: 0.04 },
        abilities: [
          { key: '1', level: 10, name: 'Void Bolt', type: 'bolt', color: '#8b5cf6', damage: 86, manaCost: 24, range: 560, width: 24, cooldown: 950 },
          {
            key: '2',
            level: 10,
            name: 'Flay',
            type: 'channel',
            color: '#5b21b6',
            damage: 30,
            manaCost: 8,
            duration: 3200,
            tickRate: 450,
            range: 570,
            width: 34,
            cooldown: 5200,
            followCaster: true,
          },
          { key: '3', level: 12, name: 'Mind Blast', type: 'ground', color: '#7c3aed', damage: 84, manaCost: 52, duration: 700, tickRate: 700, radius: 108, groundAtCursor: true, cooldown: 7200 },
          { key: '4', level: 16, name: 'Void Curse', type: 'ground', color: '#4c1d95', damage: 28, manaCost: 58, duration: 4000, tickRate: 500, radius: 118, groundAtCursor: true, cooldown: 10500 },
        ],
      },
      light: {
        name: 'Embrace the Light',
        role: 'Healer',
        description: 'Golden healing magic restores allies and bursts into holy protection.',
        bonuses: { health: 25, intellect: 4, mana: 34 },
        abilities: [
          { key: '1', level: 10, name: 'Light Heal', type: 'heal', color: '#fef3c7', healing: 92, manaCost: 34, cooldown: 1800, targetPlayer: true },
          { key: '2', level: 10, name: 'Renew', type: 'hot', color: '#fde68a', healing: 34, manaCost: 30, duration: 6000, tickRate: 1000, cooldown: 4500, targetPlayer: true },
          { key: '3', level: 12, name: 'Radiant Circle', type: 'healGround', color: '#facc15', healing: 50, manaCost: 58, duration: 5000, tickRate: 1000, radius: 125, groundAtCursor: true, cooldown: 10000 },
          { key: '4', level: 16, name: 'Holy Nova', type: 'nova', color: '#fef08a', damage: 42, healing: 58, manaCost: 46, radius: 128, cooldown: 4800 },
        ],
      },
    },
  },
  rogue: {
    unlockLevel: 10,
    specs: {
      nightblade: {
        name: 'Assassin',
        role: 'Damage',
        description: 'Invisibility openers, poison windows, and stacking bleed pressure.',
        bonuses: { agility: 7, strength: 2, attackSpeed: 0.18 },
        abilities: [
          { key: '1', level: 10, name: 'Quick Cut', type: 'strike', color: '#d8b4fe', damage: 86, energyCost: 22, cooldown: 700, range: 76 },
          { key: '2', level: 10, name: 'Assassinate', type: 'strike', color: '#f0abfc', damage: 132, energyCost: 34, cooldown: 2100, range: 82 },
          { key: '3', level: 12, name: 'Fan of Knives', type: 'nova', color: '#a78bfa', damage: 78, energyCost: 42, cooldown: 6200, radius: 142 },
          {
            key: '4',
            level: 16,
            name: 'Poison Blade',
            type: 'buff',
            color: '#86efac',
            energyCost: 28,
            cooldown: 14000,
            duration: 5000,
            poisonWindow: true,
            poisonDamage: 9,
            poisonDuration: 5000,
            poisonTickRate: 1000,
            followCaster: true,
          },
        ],
      },
      duelist: {
        name: 'Shadow',
        role: 'Damage',
        description: 'Teleport pressure, fast dagger flurries, and a short burst window.',
        bonuses: { agility: 5, strength: 4, health: 18, attackSpeed: 0.25 },
        abilities: [
          { key: '1', level: 10, name: 'Shadow Slash', type: 'strike', color: '#c084fc', damage: 82, energyCost: 20, cooldown: 750, range: 76 },
          { key: '2', level: 10, name: 'Shadow Flurry', type: 'channel', color: '#7c3aed', damage: 34, energyCost: 10, duration: CHANNEL_MAX_DURATION_MS, tickRate: 200, cooldown: 3800, range: 58, width: 48, followCaster: true },
          { key: '3', level: 12, name: 'Shadowstep', type: 'strike', color: '#a78bfa', damage: 78, energyCost: 38, cooldown: 9000, range: 260, teleportToTarget: true, postDamageMultiplier: 1.25, postDamageDuration: 2000 },
          { key: '4', level: 16, name: 'Dagger Cyclone', type: 'aura', color: '#e9d5ff', damage: 52, energyCost: 46, duration: 2000, tickRate: 500, cooldown: 12000, radius: 126, followCaster: true },
        ],
      },
    },
  },
};

const TALENT_BRANCHES = [
  { id: 'training', name: 'Training' },
  { id: 'abilities', name: 'Ability Focus' },
  { id: 'mastery', name: 'Mastery' },
];

const TALENT_NODES = [
  {
    id: 'core',
    branch: 'training',
    name: 'Core Discipline',
    maxRank: 3,
    description: 'Improves your primary stat and health.',
  },
  {
    id: 'flow',
    branch: 'training',
    name: 'Battle Flow',
    maxRank: 3,
    description: 'Improves your resource comfort and attack rhythm.',
  },
  {
    id: 'ability1',
    branch: 'abilities',
    name: 'Opening Technique',
    maxRank: 2,
    abilityKey: '1',
    damageBonus: 0.06,
    healingBonus: 0.06,
    description: 'Improves your first specialization ability.',
  },
  {
    id: 'ability2',
    branch: 'abilities',
    name: 'Second Technique',
    maxRank: 2,
    abilityKey: '2',
    damageBonus: 0.06,
    healingBonus: 0.06,
    cooldownReduction: 0.03,
    description: 'Improves your second specialization ability.',
  },
  {
    id: 'ability3',
    branch: 'abilities',
    name: 'Field Control',
    maxRank: 2,
    abilityKey: '3',
    requiresLevel: 12,
    damageBonus: 0.05,
    healingBonus: 0.05,
    cooldownReduction: 0.04,
    description: 'Improves your third specialization ability.',
  },
  {
    id: 'ability4',
    branch: 'mastery',
    name: 'Defining Technique',
    maxRank: 2,
    abilityKey: '4',
    requiresLevel: 16,
    damageBonus: 0.04,
    healingBonus: 0.04,
    durationBonus: 0.08,
    absorbBonus: 0.08,
    description: 'Improves your fourth specialization ability.',
  },
  {
    id: 'ability5',
    branch: 'mastery',
    name: 'Final Technique',
    maxRank: 2,
    abilityKey: '5',
    requiresLevel: 20,
    damageBonus: 0.08,
    healingBonus: 0.08,
    cooldownReduction: 0.05,
    durationBonus: 0.05,
    absorbBonus: 0.08,
    description: 'Improves your fifth specialization ability.',
  },
];

const SPEC_FINAL_ABILITY_LEVEL = 20;

const SPEC_FINAL_ABILITIES = {
  mage: {
    frost: { key: '5', level: SPEC_FINAL_ABILITY_LEVEL, name: 'Ice Block', type: 'buff', color: '#bae6fd', manaCost: 58, duration: 5000, rootSelf: true, invulnerable: true, regenPerSecond: 18, manaRegenPerSecond: 30, autoCombatBolt: true, autoBoltName: 'Frost Bolt', autoBoltDamage: 48, autoBoltInterval: 1000, autoBoltCombatOnly: true, cooldown: 42000, followCaster: true },
    arcane: { key: '5', level: SPEC_FINAL_ABILITY_LEVEL, name: 'Inferno Form', type: 'buff', color: '#fb923c', manaCost: 74, duration: 9000, damageMultiplier: 1.18, manaRegenPerSecond: 22, burnWindow: true, burnDamage: 11, burnDuration: 5000, burnTickRate: 1000, burnStacking: true, cooldown: 36000, followCaster: true },
  },
  hunter: {
    beastmaster: { key: '5', level: SPEC_FINAL_ABILITY_LEVEL, name: 'True Shot', type: 'shot', color: '#fef08a', damage: 165, manaCost: 72, range: 720, width: 58, pierce: true, damageTakenMultiplier: 1.22, damageTakenDuration: 7000, cooldown: 30000 },
    survival: { key: '5', level: SPEC_FINAL_ABILITY_LEVEL, name: 'Predator Focus', type: 'buff', color: '#bef264', manaCost: 66, duration: 10000, attackSpeedMultiplier: 1.35, petAttackSpeedMultiplier: 1.45, petBleedDamage: 10, petBleedDuration: 5000, damageMultiplier: 1.14, cooldown: 36000, followCaster: true },
  },
  paladin: {
    verdict: {
      key: '5',
      level: SPEC_FINAL_ABILITY_LEVEL,
      name: 'Avenging Radiance',
      type: 'buff',
      color: '#fef08a',
      manaCost: 72,
      duration: 9000,
      damageMultiplier: 1.4,
      leechPercent: 0.3,
      cooldown: 30000,
    },
    aegis: {
      key: '5',
      level: SPEC_FINAL_ABILITY_LEVEL,
      name: 'Divine Bulwark',
      type: 'buff',
      color: '#dbeafe',
      manaCost: 62,
      duration: 5000,
      invulnerable: true,
      cooldown: 45000,
    },
  },
  warrior: {
    berserker: { key: '5', level: SPEC_FINAL_ABILITY_LEVEL, name: 'Blood Frenzy', type: 'buff', color: '#ef4444', furyCost: 46, duration: 9000, furyRegenPerSecond: 14, damageMultiplier: 1.28, leechPercent: 0.22, cooldown: 34000, followCaster: true },
    ironward: { key: '5', level: SPEC_FINAL_ABILITY_LEVEL, name: 'Last Stand', type: 'buff', color: '#cbd5e1', furyCost: 42, duration: 9000, maxHealthMultiplier: 1.35, regenPerSecond: 24, damageReduction: 0.35, furyRegenPerSecond: 12, cooldown: 42000, followCaster: true },
  },
  priest: {
    void: {
      key: '5',
      level: SPEC_FINAL_ABILITY_LEVEL,
      name: 'Void Form',
      type: 'buff',
      color: '#4c1d95',
      manaCost: 76,
      duration: 5000,
      manaRegenPerSecond: 34,
      autoCombatBolt: true,
      autoBoltCombatOnly: true,
      autoBoltName: 'Void Bolt',
      autoBoltDamage: 54,
      autoBoltInterval: 500,
      cooldown: 34000,
      followCaster: true,
    },
    light: {
      key: '5',
      level: SPEC_FINAL_ABILITY_LEVEL,
      name: 'Become the Ascended',
      type: 'buff',
      color: '#fef08a',
      manaCost: 78,
      duration: 7000,
      noManaCost: true,
      healingMultiplier: 1.45,
      cooldownMultiplier: 0.55,
      cooldown: 42000,
      followCaster: true,
    },
  },
  rogue: {
    nightblade: { key: '5', level: SPEC_FINAL_ABILITY_LEVEL, name: 'Crimson Rupture', type: 'strike', color: '#dc2626', damage: 118, energyCost: 52, cooldown: 28000, bleedDamage: 16, bleedTickRate: 1000, range: 82 },
    duelist: { key: '5', level: SPEC_FINAL_ABILITY_LEVEL, name: 'Shadow Frenzy', type: 'buff', color: '#312e81', energyCost: 30, duration: 10000, cooldown: 42000, noEnergyCost: true, cooldownMultiplier: 0.35, followCaster: true },
  },
};

const BOSS_LOOT = [
  { name: 'Ancient Ember Crown', rarity: 'Rare', slot: 'head', stats: { intellect: 3, mana: 10 } },
  { name: 'Ironbark Chestguard', rarity: 'Rare', slot: 'chest', stats: { health: 25, strength: 1 } },
  { name: 'Wolf King Fang', rarity: 'Epic', slot: 'weapon', stats: { strength: 4, agility: 2 } },
  { name: 'Moonlit Trail Boots', rarity: 'Epic', slot: 'boots', stats: { agility: 4, health: 10 } },
  { name: 'Sunforged Relic', rarity: 'Epic', slot: 'trinket', stats: { mana: 15, intellect: 2 } },
  { name: 'Rift Guard Buckler', rarity: 'Rare', slot: 'offhand', stats: { health: 18, strength: 2 } },
  { name: 'Band of First Dawn', rarity: 'Rare', slot: 'ring', stats: { agility: 2, intellect: 2 } },
];

const SHOPKEEPER = {
  x: 515,
  y: 390,
  name: 'Mira',
  type: 'shopkeeper',
  interactRange: 92,
};

const RACES = {
  human: {
    name: 'Human',
    icon: User,
    skin: '#f2c7a4',
    hair: '#8b5e34',
    scale: 1,
    allowedClasses: ['mage', 'hunter', 'paladin', 'warrior', 'priest', 'rogue'],
  },
  elf: {
    name: 'Elf',
    icon: Leaf,
    skin: '#f0d6ad',
    hair: '#e9d66b',
    scale: 0.96,
    allowedClasses: ['mage', 'hunter', 'priest', 'rogue'],
  },
  dwarf: {
    name: 'Dwarf',
    icon: Hammer,
    skin: '#d6a06f',
    hair: '#9a4f2f',
    scale: 0.88,
    allowedClasses: ['paladin', 'warrior', 'hunter', 'priest', 'rogue'],
  },
  orc: {
    name: 'Orc',
    icon: Sword,
    skin: '#74a85a',
    hair: '#20251f',
    scale: 1.08,
    allowedClasses: ['warrior', 'hunter', 'rogue'],
  },
  undead: {
    name: 'Undead',
    icon: Skull,
    skin: '#cbd5c0',
    hair: '#d8dee9',
    scale: 1,
    allowedClasses: ['mage', 'warrior', 'priest', 'rogue'],
  },
};

const CLASSES = {
  mage: {
    name: 'Mage',
    icon: Wand2,
    colors: {
      robe: '#4263eb',
      trim: '#8be9fd',
      hair: '#f6d365',
      weapon: '#d7f9ff',
    },
    abilities: [
      { key: '1', level: 1, name: 'Firebolt', type: 'bolt', color: '#ff6b35', damage: 55 },
      { key: '2', level: 1, name: 'Frost Nova', type: 'nova', color: '#7dd3fc', damage: 30 },
      { key: '3', level: 4, name: 'Arcane Lance', type: 'shot', color: '#c084fc', damage: 65 },
      { key: '4', level: 8, name: 'Meteor Ring', type: 'shout', color: '#fb7185', damage: 42 },
      { key: '5', level: 12, name: 'Ice Prison', type: 'trap', color: '#bae6fd', damage: 70 },
      { key: '6', level: 16, name: 'Star Surge', type: 'bolt', color: '#fef08a', damage: 95 },
    ],
  },
  hunter: {
    name: 'Hunter',
    icon: Crosshair,
    colors: {
      robe: '#2f9e44',
      trim: '#d8b46a',
      hair: '#5f3dc4',
      weapon: '#8d6e45',
    },
    abilities: [
      { key: '1', level: 1, name: 'Piercing Shot', type: 'shot', color: '#facc15', damage: 45 },
      { key: '2', level: 1, name: 'Trap', type: 'trap', color: '#fb923c', damage: 40, duration: 15000, tickRate: 160, radius: 76, trapOffset: 120 },
      { key: '3', level: 4, name: 'Rapid Arrow', type: 'bolt', color: '#bef264', damage: 58 },
      { key: '4', level: 8, name: 'Explosive Trap', type: 'trap', color: '#fdba74', damage: 70, duration: 15000, tickRate: 160, radius: 92, trapOffset: 120 },
      { key: '5', level: 12, name: 'Volley', type: 'shout', color: '#fde047', damage: 45 },
      { key: '6', level: 16, name: 'Deadeye', type: 'shot', color: '#fefce8', damage: 110 },
    ],
  },
  paladin: {
    name: 'Paladin',
    icon: Shield,
    colors: {
      robe: '#e6c55c',
      trim: '#f8fafc',
      hair: '#8b5e34',
      weapon: '#cbd5e1',
    },
    abilities: [
      { key: '1', level: 1, name: 'Holy Strike', type: 'strike', color: '#fff3a3', damage: 45 },
      { key: '2', level: 1, name: 'Divine Shield', type: 'shield', color: '#fef08a', damage: 22 },
      { key: '3', level: 4, name: 'Judgement', type: 'bolt', color: '#fde68a', damage: 62 },
      { key: '4', level: 8, name: 'Consecration', type: 'nova', color: '#fef3c7', damage: 48 },
      { key: '5', level: 12, name: 'Hammer Toss', type: 'shot', color: '#e5e7eb', damage: 82 },
      { key: '6', level: 16, name: 'Radiant Burst', type: 'shout', color: '#fef08a', damage: 72 },
    ],
  },
  warrior: {
    name: 'Warrior',
    icon: Sword,
    colors: {
      robe: '#b42318',
      trim: '#64748b',
      hair: '#2f221d',
      weapon: '#d1d5db',
    },
    abilities: [
      { key: '1', level: 1, name: 'Cleave', type: 'cleave', color: '#f97316', damage: 48 },
      { key: '2', level: 1, name: 'Battle Shout', type: 'shout', color: '#ef4444', damage: 25 },
      { key: '3', level: 4, name: 'Charge Slash', type: 'strike', color: '#fb923c', damage: 65 },
      { key: '4', level: 8, name: 'Whirlwind', type: 'nova', color: '#f87171', damage: 50 },
      { key: '5', level: 12, name: 'Ground Breaker', type: 'trap', color: '#a16207', damage: 80 },
      { key: '6', level: 16, name: 'Execute', type: 'shot', color: '#fecaca', damage: 120 },
    ],
  },
  priest: {
    name: 'Priest',
    icon: HeartPulse,
    colors: {
      robe: '#f8fafc',
      trim: '#facc15',
      hair: '#d8b4fe',
      weapon: '#fde68a',
    },
    abilities: [
      { key: '1', level: 1, name: 'Smite', type: 'bolt', color: '#fef3c7', damage: 48 },
      { key: '2', level: 1, name: 'Holy Nova', type: 'nova', color: '#fde68a', damage: 28 },
      { key: '3', level: 4, name: 'Mind Spike', type: 'shot', color: '#c4b5fd', damage: 62 },
      { key: '4', level: 8, name: 'Sanctuary', type: 'shield', color: '#fef08a', damage: 34 },
      { key: '5', level: 12, name: 'Penance', type: 'bolt', color: '#e9d5ff', damage: 78 },
      { key: '6', level: 16, name: 'Divine Wrath', type: 'shout', color: '#fff7ed', damage: 82 },
    ],
  },
  rogue: {
    name: 'Rogue',
    icon: Sword,
    colors: {
      robe: '#312e81',
      trim: '#c084fc',
      hair: '#1f2937',
      weapon: '#e5e7eb',
    },
    abilities: [
      { key: '1', level: 1, name: 'Quick Stab', type: 'strike', color: '#d8b4fe', damage: 44 },
      { key: '2', level: 1, name: 'Blade Fan', type: 'cleave', color: '#a78bfa', damage: 34 },
      { key: '3', level: 4, name: 'Poison Knife', type: 'shot', color: '#86efac', damage: 58 },
      { key: '4', level: 8, name: 'Smoke Bomb', type: 'trap', color: '#94a3b8', damage: 48 },
      { key: '5', level: 12, name: 'Ambush', type: 'strike', color: '#f0abfc', damage: 88 },
      { key: '6', level: 16, name: 'Eviscerate', type: 'shot', color: '#f5d0fe', damage: 118 },
    ],
  },
};

const CLASS_NAME_POOLS = {
  mage: ['Aetherion', 'Lyra Spellwind', 'Vaelis', 'Mira Starfall', 'Eldrin'],
  hunter: ['Rowan Swiftshot', 'Kael Thorn', 'Ashen Vale', 'Nira Wildmark', 'Bryn'],
  paladin: ['Aurel Dawnshield', 'Ser Caldus', 'Tirion Vale', 'Maren Lightward', 'Garran'],
  warrior: ['Brakka Ironhand', 'Duran Steelborn', 'Rokar', 'Hilda Axebreaker', 'Torvik'],
  priest: ['Elowen Lightcall', 'Seren Dawn', 'Iria Solace', 'Neris', 'Calen Vow'],
  rogue: ['Nyx Shade', 'Vera Quickstep', 'Silas Dusk', 'Kira Vex', 'Ren Blackvale'],
};

const CHARACTER_SPRITE_SIZE = 48;
const CHARACTER_SPRITE_DRAW_SIZE = 72;
const CHARACTER_SPRITE_COLUMNS = 6;
const CHARACTER_SPRITE_EXPECTED_WIDTH = CHARACTER_SPRITE_SIZE * CHARACTER_SPRITE_COLUMNS;
const CHARACTER_SPRITE_EXPECTED_HEIGHT = CHARACTER_SPRITE_SIZE * 4;
const CHARACTER_SPRITE_VERSION = 'attack-v3';
const CHARACTER_SPRITE_VARIANTS = ['male', 'female'];
const CHARACTER_SPRITE_ROWS = {
  down: 0,
  left: 1,
  right: 2,
  up: 3,
};
const CHARACTER_SPRITES = new globalThis.Map();
const CHARACTER_SPRITE_LOADS = new globalThis.Map();
const CHARACTER_TINTED_SPRITES = new globalThis.Map();
const CHARACTER_SPRITE_SOURCE_PALETTES = {
  priest: { skin: '#f2c7a4', skinShade: '#d99a72', hair: '#b794f4', robe: '#f8fafc', trim: '#facc15' },
  paladin: { skin: '#f2c7a4', skinShade: '#d99a72', hair: '#facc15', robe: '#f8fafc', trim: '#facc15' },
  hunter: { skin: '#f2c7a4', skinShade: '#d99a72', hair: '#2f221d', robe: '#365c2d', trim: '#d6a354' },
  mage: { skin: '#f2c7a4', skinShade: '#d99a72', hair: '#2563eb', robe: '#1d4ed8', trim: '#facc15' },
  rogue: { skin: '#f2c7a4', skinShade: '#d99a72', hair: '#111827', robe: '#1f2937', trim: '#9ca3af' },
  warrior: { skin: '#f2c7a4', skinShade: '#d99a72', hair: '#8b5a2b', robe: '#7f1d1d', trim: '#cbd5e1' },
};
const CHARACTER_LAYER_ORDER = ['cape', 'base', 'hair', 'beard', 'outfit', 'weapon'];
const CHARACTER_LAYER_DIRS = {
  base: 'base',
  hair: 'hair',
  beard: 'beard',
  outfit: 'outfits',
  weapon: 'weapons',
  cape: 'capes',
};
const CHARACTER_LAYER_IMAGES = new globalThis.Map();
const CHARACTER_LAYER_LOADS = new globalThis.Map();
const ENEMY_SPRITES = new globalThis.Map();
const ENEMY_SPRITE_LOADS = new globalThis.Map();
const PET_SPRITES = new globalThis.Map();
const PET_SPRITE_LOADS = new globalThis.Map();
const PET_SPRITE_VERSION = 'pet-attack-v2';
const ENEMY_SPRITE_VERSION = 'tamzia-mobs-v1';
const SHOW_MAP_ENEMY_DOTS = false;
const MAP_CANVAS_REDRAW_MS = 520;
function enemySpriteConfig(id, boss = false) {
  return {
    path: `assets/enemies/${id}.png`,
    frameWidth: boss ? 96 : 64,
    frameHeight: boss ? 96 : 64,
    frameCount: 4,
    drawWidth: boss ? 148 : 76,
    drawHeight: boss ? 148 : 76,
    yOffset: boss ? -112 : -50,
  };
}

function dungeonEnemySpriteConfig(id) {
  return {
    ...enemySpriteConfig(id),
    drawWidth: 94,
    drawHeight: 94,
    yOffset: -66,
  };
}

function dungeonBossSpriteConfig(id) {
  return {
    ...enemySpriteConfig(id, true),
    drawWidth: 166,
    drawHeight: 166,
    yOffset: -126,
  };
}

const ENEMY_SPRITE_CONFIG = {
  wolf: enemySpriteConfig('wolf'),
  kobold: enemySpriteConfig('kobold'),
  bandit: enemySpriteConfig('bandit'),
  undead: enemySpriteConfig('undead'),
  'restless-dead': enemySpriteConfig('restless-dead'),
  'snow-wolf': enemySpriteConfig('snow-wolf'),
  'frost-trogg': enemySpriteConfig('frost-trogg'),
  'cave-spider': enemySpriteConfig('cave-spider'),
  'grave-rat': enemySpriteConfig('grave-rat'),
  plaguehound: enemySpriteConfig('plaguehound'),
  'forest-sprite': enemySpriteConfig('forest-sprite'),
  'corrupted-treant': enemySpriteConfig('corrupted-treant'),
  nightstalker: enemySpriteConfig('nightstalker'),
  plainstrider: enemySpriteConfig('plainstrider'),
  scorpion: enemySpriteConfig('scorpion'),
  quilboar: enemySpriteConfig('quilboar'),
  'road-bandit': enemySpriteConfig('road-bandit'),
  'dire-wolf': enemySpriteConfig('dire-wolf'),
  'stone-gnoll': enemySpriteConfig('stone-gnoll'),
  'ember-wraith': enemySpriteConfig('ember-wraith'),
  'elder-briarheart': enemySpriteConfig('elder-briarheart', true),
  'granite-matriarch': enemySpriteConfig('granite-matriarch', true),
  'crypt-warden': enemySpriteConfig('crypt-warden', true),
  'moonshade-stag': enemySpriteConfig('moonshade-stag', true),
  'bloodtusk-chief': enemySpriteConfig('bloodtusk-chief', true),
  'varro-the-tollkeeper': enemySpriteConfig('varro-the-tollkeeper', true),
  'thornmaw-alpha': enemySpriteConfig('thornmaw-alpha', true),
  'granite-ogre': enemySpriteConfig('granite-ogre', true),
  'ash-witch': enemySpriteConfig('ash-witch', true),
  'cave-stalker': dungeonEnemySpriteConfig('cave-stalker'),
  'magma-crawler': dungeonEnemySpriteConfig('magma-crawler'),
  'deep-burrower': dungeonEnemySpriteConfig('deep-burrower'),
  'obsidian-sentinel': dungeonEnemySpriteConfig('obsidian-sentinel'),
  'reedwater-marauder': enemySpriteConfig('reedwater-marauder'),
  'bramblehide-bear': enemySpriteConfig('bramblehide-bear'),
  'moonbrook-prowler': enemySpriteConfig('moonbrook-prowler'),
  'redscar-highwayman': enemySpriteConfig('redscar-highwayman'),
  'saltspine-crawler': enemySpriteConfig('saltspine-crawler'),
  'gloomfang-matriarch': dungeonBossSpriteConfig('gloomfang-matriarch'),
  'lava-forged-warden': dungeonBossSpriteConfig('lava-forged-warden'),
  'crystal-horror': dungeonBossSpriteConfig('crystal-horror'),
  'rift-heart': dungeonBossSpriteConfig('rift-heart'),
  'old-quarry-giant': enemySpriteConfig('old-quarry-giant', true),
  'tideglass-matriarch': enemySpriteConfig('tideglass-matriarch', true),
};

const PET_SPRITE_CONFIG = {
  human: { path: 'assets/pets/human.png', frameWidth: 64, frameHeight: 64, frameCount: 6, drawWidth: 82, drawHeight: 82, yOffset: -42 },
  elf: { path: 'assets/pets/elf.png', frameWidth: 64, frameHeight: 64, frameCount: 6, drawWidth: 82, drawHeight: 82, yOffset: -42 },
  dwarf: { path: 'assets/pets/dwarf.png', frameWidth: 64, frameHeight: 64, frameCount: 6, drawWidth: 82, drawHeight: 82, yOffset: -42 },
  orc: { path: 'assets/pets/orc.png', frameWidth: 64, frameHeight: 64, frameCount: 6, drawWidth: 86, drawHeight: 86, yOffset: -44 },
};

const CUSTOMIZATION = {
  skin: ['#f2c7a4', '#d6a06f', '#f0d6ad', '#74a85a', '#cbd5c0'],
  hair: ['#8b5e34', '#f6d365', '#2f221d', '#d8b4fe', '#d8dee9'],
  robe: ['#4263eb', '#2f9e44', '#e6c55c', '#b42318', '#f8fafc'],
  trim: ['#8be9fd', '#f8fafc', '#facc15', '#64748b', '#c084fc'],
};

const APPEARANCE_CHOICES = {
  gender: [
    { id: 'male', label: 'Male' },
    { id: 'female', label: 'Female' },
  ],
  hairStyle: [
    { id: 'short', label: 'Short' },
    { id: 'long', label: 'Long' },
    { id: 'hooded', label: 'Hood' },
  ],
  beard: [
    { id: 'none', label: 'None' },
    { id: 'short', label: 'Short' },
    { id: 'full', label: 'Full' },
  ],
  outfitVariant: [
    { id: 'classic', label: 'Classic' },
    { id: 'veteran', label: 'Veteran' },
    { id: 'dark', label: 'Dark' },
  ],
  weaponVariant: [
    { id: 'classic', label: 'Classic' },
    { id: 'ornate', label: 'Ornate' },
    { id: 'shadow', label: 'Shadow' },
  ],
  capeStyle: [
    { id: 'none', label: 'None' },
    { id: 'short', label: 'Short' },
    { id: 'long', label: 'Long' },
  ],
};

const TREES = [
  [260, 240], [430, 380], [620, 250], [940, 440], [1180, 280], [1450, 520],
  [1760, 330], [2040, 570], [2380, 410], [2710, 650], [3090, 360],
  [360, 920], [720, 760], [1010, 1050], [1390, 900], [1680, 1120],
  [2090, 890], [2460, 1010], [2860, 910], [3240, 1180],
  [520, 1540], [860, 1320], [1230, 1690], [1560, 1450], [1930, 1600],
  [2320, 1370], [2680, 1700], [3120, 1490],
  [390, 2050], [760, 1900], [1130, 2180], [1510, 1990], [1880, 2110],
  [2260, 1920], [2630, 2200], [3070, 2020], [3370, 2140],
];

const ROCKS = [
  [780, 520], [1320, 650], [2180, 260], [3010, 780], [460, 1280],
  [1120, 1370], [1810, 760], [2530, 1320], [3360, 980], [940, 2040],
  [2110, 2180], [2890, 1880],
];

const NPCS = [
  { x: 560, y: 590, name: 'Lina', color: '#f97316' },
  { x: 1710, y: 1340, name: 'Marek', color: '#06b6d4' },
  { x: 2920, y: 1540, name: 'Sera', color: '#a855f7' },
];

export {
  PLAYER,
  ENEMY,
  SAVE_KEY,
  FRIENDS_KEY,
  REMEMBER_LOGIN_KEY,
  ADMIN_EMAILS,
  MAX_LEVEL,
  ENEMY_XP,
  BOSS_XP,
  BOSS_SPAWN_MIN,
  BOSS_SPAWN_MAX,
  BOSS_RESPAWN_DELAY,
  COLYSEUS_INPUT_MS,
  COLYSEUS_RECONNECT_MS,
  COLYSEUS_MAX_RECONNECT_ATTEMPTS,
  REMOTE_PLAYER_LEAD_MS,
  REMOTE_PLAYER_SMOOTHING,
  REMOTE_PLAYER_SNAP_DISTANCE,
  AUTO_ATTACK_BASE_COOLDOWN_MS,
  AUTO_ATTACK_MIN_COOLDOWN_MS,
  AUTO_ATTACK_MAX_COOLDOWN_MS,
  CHANNEL_MAX_DURATION_MS,
  BASE_STATS,
  STAT_DESCRIPTIONS,
  INVENTORY_CAPACITY,
  RECALL_ITEM_ID,
  RECALL_CAST_MS,
  RECALL_ITEM,
  STARTER_HEALTH_POTION_ID,
  POTION_COOLDOWN_MS,
  BANK_CAPACITY,
  AUCTION_LISTINGS_KEY,
  STARTER_HEALTH_POTION,
  POTION_TEMPLATES,
  CITY_VENDOR_STOCK,
  PROFESSIONS,
  PROFESSION_BY_ID,
  ABILITY_BAR_SLOTS,
  TALENT_UNLOCK_LEVEL,
  HUNTER_PET,
  EQUIPMENT_SLOTS,
  STAT_GROWTH,
  ABILITY_MANA_COST,
  ABILITY_COOLDOWNS,
  getAbilityTickRateMs,
  shouldEffectFollowCaster,
  TALENTS,
  TALENT_BRANCHES,
  TALENT_NODES,
  SPEC_FINAL_ABILITY_LEVEL,
  SPEC_FINAL_ABILITIES,
  BOSS_LOOT,
  SHOPKEEPER,
  RACES,
  CLASSES,
  CLASS_NAME_POOLS,
  CHARACTER_SPRITE_SIZE,
  CHARACTER_SPRITE_DRAW_SIZE,
  CHARACTER_SPRITE_COLUMNS,
  CHARACTER_SPRITE_EXPECTED_WIDTH,
  CHARACTER_SPRITE_EXPECTED_HEIGHT,
  CHARACTER_SPRITE_VERSION,
  CHARACTER_SPRITE_VARIANTS,
  CHARACTER_SPRITE_ROWS,
  CHARACTER_SPRITES,
  CHARACTER_SPRITE_LOADS,
  CHARACTER_TINTED_SPRITES,
  CHARACTER_SPRITE_SOURCE_PALETTES,
  CHARACTER_LAYER_ORDER,
  CHARACTER_LAYER_DIRS,
  CHARACTER_LAYER_IMAGES,
  CHARACTER_LAYER_LOADS,
  ENEMY_SPRITES,
  ENEMY_SPRITE_LOADS,
  PET_SPRITES,
  PET_SPRITE_LOADS,
  PET_SPRITE_VERSION,
  ENEMY_SPRITE_VERSION,
  SHOW_MAP_ENEMY_DOTS,
  MAP_CANVAS_REDRAW_MS,
  enemySpriteConfig,
  dungeonEnemySpriteConfig,
  dungeonBossSpriteConfig,
  ENEMY_SPRITE_CONFIG,
  PET_SPRITE_CONFIG,
  CUSTOMIZATION,
  APPEARANCE_CHOICES,
  TREES,
  ROCKS,
  NPCS,
};
